! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE ECTRANS_BLAS_BATCHED_MOD

USE EC_PARKIND, ONLY : JPRD, JPRM, JPIM
USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INT, C_DOUBLE, C_FLOAT, C_PTR, C_F_POINTER

IMPLICIT NONE

PRIVATE

PUBLIC :: GEMM_BATCHED

#ifdef HAVE_BATCHED_BLAS
! CBLAS constants
INTEGER(KIND=C_INT), PARAMETER :: CBLAS_COLMAJOR = 102
INTEGER(KIND=C_INT), PARAMETER :: CBLAS_NOTRANS  = 111
INTEGER(KIND=C_INT), PARAMETER :: CBLAS_TRANS    = 112

INTERFACE
  SUBROUTINE CBLAS_DGEMM_BATCH(LAYOUT, TRANSA, TRANSB, M, N, K, ALPHA, &
      A, LDA, B, LDB, BETA, C, LDC, GROUP_COUNT, GROUP_SIZE) &
      BIND(C, NAME='cblas_dgemm_batch')
    USE ISO_C_BINDING
    INTEGER(C_INT), VALUE :: LAYOUT
    INTEGER(C_INT), INTENT(IN) :: TRANSA(*), TRANSB(*)
    INTEGER(C_INT), INTENT(IN) :: M(*), N(*), K(*)
    REAL(C_DOUBLE), INTENT(IN) :: ALPHA(*), BETA(*)
    TYPE(C_PTR), INTENT(IN) :: A(*)
    INTEGER(C_INT), INTENT(IN) :: LDA(*)
    TYPE(C_PTR), INTENT(IN) :: B(*)
    INTEGER(C_INT), INTENT(IN) :: LDB(*)
    TYPE(C_PTR), INTENT(IN) :: C(*)
    INTEGER(C_INT), INTENT(IN) :: LDC(*)
    INTEGER(C_INT), VALUE :: GROUP_COUNT
    INTEGER(C_INT), INTENT(IN) :: GROUP_SIZE(*)
  END SUBROUTINE CBLAS_DGEMM_BATCH

  SUBROUTINE CBLAS_SGEMM_BATCH(LAYOUT, TRANSA, TRANSB, M, N, K, ALPHA, &
      A, LDA, B, LDB, BETA, C, LDC, GROUP_COUNT, GROUP_SIZE) &
      BIND(C, NAME='cblas_sgemm_batch')
    USE ISO_C_BINDING
    INTEGER(C_INT), VALUE :: LAYOUT
    INTEGER(C_INT), INTENT(IN) :: TRANSA(*), TRANSB(*)
    INTEGER(C_INT), INTENT(IN) :: M(*), N(*), K(*)
    REAL(C_FLOAT), INTENT(IN) :: ALPHA(*), BETA(*)
    TYPE(C_PTR), INTENT(IN) :: A(*)
    INTEGER(C_INT), INTENT(IN) :: LDA(*)
    TYPE(C_PTR), INTENT(IN) :: B(*)
    INTEGER(C_INT), INTENT(IN) :: LDB(*)
    TYPE(C_PTR), INTENT(IN) :: C(*)
    INTEGER(C_INT), INTENT(IN) :: LDC(*)
    INTEGER(C_INT), VALUE :: GROUP_COUNT
    INTEGER(C_INT), INTENT(IN) :: GROUP_SIZE(*)
  END SUBROUTINE CBLAS_SGEMM_BATCH
END INTERFACE
#endif

INTERFACE GEMM_BATCHED
  MODULE PROCEDURE GEMM_BATCHED_DP
  MODULE PROCEDURE GEMM_BATCHED_SP
END INTERFACE

CONTAINS

#ifdef HAVE_BATCHED_BLAS
PURE FUNCTION TRIPLET_LESS(M1, N1, K1, LDA1, LDB1, LDC1, &
                           M2, N2, K2, LDA2, LDB2, LDC2) RESULT(R)
  INTEGER(KIND=JPIM), INTENT(IN) :: M1, N1, K1, LDA1, LDB1, LDC1
  INTEGER(KIND=JPIM), INTENT(IN) :: M2, N2, K2, LDA2, LDB2, LDC2
  LOGICAL :: R
  IF (M1   /= M2  ) THEN
    R = (M1   < M2  )
    RETURN
  ENDIF
  IF (N1   /= N2  ) THEN
    R = (N1   < N2  )
    RETURN
  ENDIF
  IF (K1   /= K2  ) THEN
    R = (K1   < K2  )
    RETURN
  ENDIF
  IF (LDA1 /= LDA2) THEN
    R = (LDA1 < LDA2)
    RETURN
  ENDIF
  IF (LDB1 /= LDB2) THEN
    R = (LDB1 < LDB2)
    RETURN
  ENDIF
  IF (LDC1 /= LDC2) THEN
    R = (LDC1 < LDC2)
    RETURN
  ENDIF
  R = .FALSE.   ! all equal
END FUNCTION TRIPLET_LESS
#endif

SUBROUTINE GEMM_BATCHED_DP(TRANSA, TRANSB, M, N, K, ALPHA, BETA, &
    A_PTRS, LDA, B_PTRS, LDB, C_PTRS, LDC, BATCH_COUNT)
  CHARACTER,          INTENT(IN) :: TRANSA, TRANSB
  INTEGER(KIND=JPIM), INTENT(IN) :: BATCH_COUNT
  INTEGER(KIND=JPIM), INTENT(IN) :: M(*), N(*), K(*), LDA(*), LDB(*), LDC(*)
  REAL(KIND=JPRD),    INTENT(IN) :: ALPHA, BETA
  TYPE(C_PTR),        INTENT(IN) :: A_PTRS(*), B_PTRS(*), C_PTRS(*)

#ifdef HAVE_BATCHED_BLAS
  INTEGER(KIND=C_INT) :: TRANSA_C(BATCH_COUNT), TRANSB_C(BATCH_COUNT)
  INTEGER(KIND=C_INT) :: GROUP_SIZE(BATCH_COUNT)
  INTEGER(KIND=C_INT) :: MC(BATCH_COUNT), NC(BATCH_COUNT), KC(BATCH_COUNT)
  INTEGER(KIND=C_INT) :: LDAC(BATCH_COUNT), LDBC(BATCH_COUNT), LDCC(BATCH_COUNT)
  REAL(KIND=C_DOUBLE) :: ALPHAC(BATCH_COUNT), BETAC(BATCH_COUNT)
  TYPE(C_PTR) :: A_PERM(BATCH_COUNT), B_PERM(BATCH_COUNT), C_PERM(BATCH_COUNT)
  INTEGER(KIND=JPIM) :: PERM(BATCH_COUNT)
  INTEGER(KIND=JPIM) :: I, II, J, GROUP_COUNT
  INTEGER(KIND=C_INT) :: TRA, TRB
  LOGICAL :: SAME

  IF (BATCH_COUNT <= 0) RETURN

  TRA = MERGE(CBLAS_NOTRANS, CBLAS_TRANS, TRANSA == 'N' .OR. TRANSA == 'n')
  TRB = MERGE(CBLAS_NOTRANS, CBLAS_TRANS, TRANSB == 'N' .OR. TRANSB == 'n')

  ! Identity permutation
  DO I = 1, BATCH_COUNT
    PERM(I) = I
  ENDDO

  ! Insertion sort PERM by (M, N, K, LDA, LDB, LDC) ascending.
  ! Should be cheap because inputs are nearly sorted
  DO I = 2, BATCH_COUNT
    II = PERM(I)
    J = I - 1
    DO WHILE (J >= 1)
      IF (.NOT. TRIPLET_LESS(M(II), N(II), K(II), LDA(II), LDB(II), LDC(II), &
                             M(PERM(J)), N(PERM(J)), K(PERM(J)), &
                             LDA(PERM(J)), LDB(PERM(J)), LDC(PERM(J)))) EXIT
      PERM(J+1) = PERM(J)
      J = J - 1
    ENDDO
    PERM(J+1) = II
  ENDDO

  ! Apply permutation to pointer arrays (groups-concatenated layout)
  DO I = 1, BATCH_COUNT
    A_PERM(I) = A_PTRS(PERM(I))
    B_PERM(I) = B_PTRS(PERM(I))
    C_PERM(I) = C_PTRS(PERM(I))
  ENDDO

  ! Scan sorted triplets, build per-group shape arrays
  GROUP_COUNT = 0
  DO I = 1, BATCH_COUNT
    II = PERM(I)
    IF (I == 1) THEN
      SAME = .FALSE.
    ELSE
      J = PERM(I-1)
      SAME = (M(II)   == M(J)   .AND. N(II)   == N(J)   .AND. K(II)   == K(J)   .AND. &
              LDA(II) == LDA(J) .AND. LDB(II) == LDB(J) .AND. LDC(II) == LDC(J))
    ENDIF
    IF (SAME) THEN
      GROUP_SIZE(GROUP_COUNT) = GROUP_SIZE(GROUP_COUNT) + 1
    ELSE
      GROUP_COUNT = GROUP_COUNT + 1
      MC(GROUP_COUNT) = M(II)
      NC(GROUP_COUNT) = N(II)
      KC(GROUP_COUNT) = K(II)
      LDAC(GROUP_COUNT) = LDA(II)
      LDBC(GROUP_COUNT) = LDB(II)
      LDCC(GROUP_COUNT) = LDC(II)
      TRANSA_C(GROUP_COUNT) = TRA
      TRANSB_C(GROUP_COUNT) = TRB
      ALPHAC(GROUP_COUNT) = ALPHA
      BETAC(GROUP_COUNT) = BETA
      GROUP_SIZE(GROUP_COUNT) = 1
    ENDIF
  ENDDO

  CALL CBLAS_DGEMM_BATCH(CBLAS_COLMAJOR, TRANSA_C, TRANSB_C, &
      MC, NC, KC, ALPHAC, A_PERM, LDAC, B_PERM, LDBC, BETAC, C_PERM, LDCC, &
      GROUP_COUNT, GROUP_SIZE)
#else
  ! OMP-parallelize across triplets, with output to different C buffers
  INTEGER(KIND=JPIM) :: I
  REAL(KIND=JPRD), POINTER :: A_PTR2D(:,:), B_PTR2D(:,:), C_PTR2D(:,:)

  !$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) DEFAULT(SHARED) &
  !$OMP   PRIVATE(I, A_PTR2D, B_PTR2D, C_PTR2D)
  DO I = 1, BATCH_COUNT
    CALL C_F_POINTER(A_PTRS(I), A_PTR2D, [LDA(I), K(I)])
    CALL C_F_POINTER(B_PTRS(I), B_PTR2D, [LDB(I), N(I)])
    CALL C_F_POINTER(C_PTRS(I), C_PTR2D, [LDC(I), N(I)])
    CALL DGEMM(TRANSA, TRANSB, M(I), N(I), K(I), ALPHA, &
        A_PTR2D, LDA(I), B_PTR2D, LDB(I), BETA, C_PTR2D, LDC(I))
  ENDDO
  !$OMP END PARALLEL DO
#endif

END SUBROUTINE GEMM_BATCHED_DP

SUBROUTINE GEMM_BATCHED_SP(TRANSA, TRANSB, M, N, K, ALPHA, BETA, &
    A_PTRS, LDA, B_PTRS, LDB, C_PTRS, LDC, BATCH_COUNT)
  CHARACTER,          INTENT(IN) :: TRANSA, TRANSB
  INTEGER(KIND=JPIM), INTENT(IN) :: BATCH_COUNT
  INTEGER(KIND=JPIM), INTENT(IN) :: M(*), N(*), K(*), LDA(*), LDB(*), LDC(*)
  REAL(KIND=JPRM),    INTENT(IN) :: ALPHA, BETA
  TYPE(C_PTR),        INTENT(IN) :: A_PTRS(*), B_PTRS(*), C_PTRS(*)

#ifdef HAVE_BATCHED_BLAS
  INTEGER(KIND=C_INT) :: TRANSA_C(BATCH_COUNT), TRANSB_C(BATCH_COUNT)
  INTEGER(KIND=C_INT) :: GROUP_SIZE(BATCH_COUNT)
  INTEGER(KIND=C_INT) :: MC(BATCH_COUNT), NC(BATCH_COUNT), KC(BATCH_COUNT)
  INTEGER(KIND=C_INT) :: LDAC(BATCH_COUNT), LDBC(BATCH_COUNT), LDCC(BATCH_COUNT)
  REAL(KIND=C_FLOAT) :: ALPHAC(BATCH_COUNT), BETAC(BATCH_COUNT)
  ! Per-triplet pointer arrays in groups-concatenated order
  TYPE(C_PTR) :: A_PERM(BATCH_COUNT), B_PERM(BATCH_COUNT), C_PERM(BATCH_COUNT)
  INTEGER(KIND=JPIM) :: PERM(BATCH_COUNT)
  INTEGER(KIND=JPIM) :: I, II, J, GROUP_COUNT
  INTEGER(KIND=C_INT) :: TRA, TRB
  LOGICAL :: SAME

  IF (BATCH_COUNT <= 0) RETURN

  TRA = MERGE(CBLAS_NOTRANS, CBLAS_TRANS, TRANSA == 'N' .OR. TRANSA == 'n')
  TRB = MERGE(CBLAS_NOTRANS, CBLAS_TRANS, TRANSB == 'N' .OR. TRANSB == 'n')

  ! Identity permutation
  DO I = 1, BATCH_COUNT
    PERM(I) = I
  ENDDO

  ! Insertion sort PERM by (M, N, K, LDA, LDB, LDC) ascending
  DO I = 2, BATCH_COUNT
    II = PERM(I)
    J = I - 1
    DO WHILE (J >= 1)
      IF (.NOT. TRIPLET_LESS(M(II), N(II), K(II), LDA(II), LDB(II), LDC(II), &
                             M(PERM(J)), N(PERM(J)), K(PERM(J)), &
                             LDA(PERM(J)), LDB(PERM(J)), LDC(PERM(J)))) EXIT
      PERM(J+1) = PERM(J)
      J = J - 1
    ENDDO
    PERM(J+1) = II
  ENDDO

  ! Apply permutation to pointer arrays
  DO I = 1, BATCH_COUNT
    A_PERM(I) = A_PTRS(PERM(I))
    B_PERM(I) = B_PTRS(PERM(I))
    C_PERM(I) = C_PTRS(PERM(I))
  ENDDO

  ! Scan sorted triplets, build per-group shape arrays
  GROUP_COUNT = 0
  DO I = 1, BATCH_COUNT
    II = PERM(I)
    IF (I == 1) THEN
      SAME = .FALSE.
    ELSE
      J = PERM(I-1)
      SAME = (M(II)   == M(J)   .AND. N(II)   == N(J)   .AND. K(II)   == K(J)   .AND. &
              LDA(II) == LDA(J) .AND. LDB(II) == LDB(J) .AND. LDC(II) == LDC(J))
    ENDIF
    IF (SAME) THEN
      GROUP_SIZE(GROUP_COUNT) = GROUP_SIZE(GROUP_COUNT) + 1
    ELSE
      GROUP_COUNT = GROUP_COUNT + 1
      MC(GROUP_COUNT) = M(II)
      NC(GROUP_COUNT) = N(II)
      KC(GROUP_COUNT) = K(II)
      LDAC(GROUP_COUNT) = LDA(II)
      LDBC(GROUP_COUNT) = LDB(II)
      LDCC(GROUP_COUNT) = LDC(II)
      TRANSA_C(GROUP_COUNT) = TRA
      TRANSB_C(GROUP_COUNT) = TRB
      ALPHAC(GROUP_COUNT) = ALPHA
      BETAC(GROUP_COUNT) = BETA
      GROUP_SIZE(GROUP_COUNT) = 1
    ENDIF
  ENDDO

  CALL CBLAS_SGEMM_BATCH(CBLAS_COLMAJOR, TRANSA_C, TRANSB_C, &
      MC, NC, KC, ALPHAC, A_PERM, LDAC, B_PERM, LDBC, BETAC, C_PERM, LDCC, &
      GROUP_COUNT, GROUP_SIZE)
#else
  INTEGER(KIND=JPIM) :: I
  REAL(KIND=JPRM), POINTER :: A_PTR2D(:,:), B_PTR2D(:,:), C_PTR2D(:,:)

  !$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) DEFAULT(SHARED) &
  !$OMP   PRIVATE(I, A_PTR2D, B_PTR2D, C_PTR2D)
  DO I = 1, BATCH_COUNT
    CALL C_F_POINTER(A_PTRS(I), A_PTR2D, [LDA(I), K(I)])
    CALL C_F_POINTER(B_PTRS(I), B_PTR2D, [LDB(I), N(I)])
    CALL C_F_POINTER(C_PTRS(I), C_PTR2D, [LDC(I), N(I)])
    CALL SGEMM(TRANSA, TRANSB, M(I), N(I), K(I), ALPHA, &
        A_PTR2D, LDA(I), B_PTR2D, LDB(I), BETA, C_PTR2D, LDC(I))
  ENDDO
  !$OMP END PARALLEL DO
#endif

END SUBROUTINE GEMM_BATCHED_SP

END MODULE ECTRANS_BLAS_BATCHED_MOD
