! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE LEINV_BATCHED_MOD
CONTAINS
SUBROUTINE LEINV_BATCHED(KF_OUT_LT, NBATCH, &
    KFC_VALS, KIFC_VALS, KDGLU_VALS, ILA_VALS, ILS_VALS, &
    ISKIP_VALS, ISL_VALS, KMLOC_VALS, &
    RPNMA_PTRS, RPNMS_PTRS, &
    ZWORK_BA, ZWORK_BS, ZWORK_CA, ZWORK_CS)

! Batched LEINV kernel: packs B matrices from PIA and calls batched GEMM
! for all wavenumbers (both anti- and symmetric, fused), then unpacks C to
! ZAOA1/ZSOA1.
!
! Antisymmetric: GEMM('N','N', KDGLU, KIFC, ILA, 1.0, RPNMA, KDGLU, ZBA, ILA, 0.0, ZC, KDGLU)
!   then ZAOA1(JK, ISL+JI-1) = ZC(JI, IFLD)   (transpose)
!
! Symmetric:     GEMM('N','N', KDGLU, KIFC, ILS, 1.0, RPNMS, KDGLU, ZBS, ILS, 0.0, ZC, KDGLU)
!   then PSOA1(JK, ISL+JI-1) = ZC(JI, IFLD)   (transpose)

USE PARKIND1  ,ONLY : JPIM, JPRB, JPRD, JPRM
USE ECTRANS_BLAS_MOD, ONLY : GEMM
USE ECTRANS_BLAS_BATCHED_MOD, ONLY : GEMM_BATCHED
USE TPM_FLT, ONLY : S
USE BUTTERFLY_ALG_MOD, ONLY : MULT_BUTM
USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_PTR, C_LOC, C_F_POINTER

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KF_OUT_LT
INTEGER(KIND=JPIM), INTENT(IN) :: NBATCH
INTEGER(KIND=JPIM), INTENT(IN) :: KFC_VALS(*), KIFC_VALS(*), KDGLU_VALS(*)
INTEGER(KIND=JPIM), INTENT(IN) :: ILA_VALS(*), ILS_VALS(*)
INTEGER(KIND=JPIM), INTENT(IN) :: ISKIP_VALS(*), ISL_VALS(*), KMLOC_VALS(*)
TYPE(C_PTR), INTENT(IN) :: RPNMA_PTRS(*), RPNMS_PTRS(*)
REAL(KIND=JPRB), TARGET, INTENT(IN) :: ZWORK_BA(*), ZWORK_BS(*)
REAL(KIND=JPRB), TARGET, INTENT(INOUT) :: ZWORK_CA(*), ZWORK_CS(*)

INTEGER(KIND=JPIM) :: I, KMLOC, KIFC, KDGLU, ILA, ILS, ITHRESHOLD
INTEGER(KIND=JPIM) :: IOFF_BA, IOFF_BS, IOFF_C
INTEGER(KIND=JPIM) :: NG    ! combined anti + sym batch count
INTEGER(KIND=JPIM) :: M(2*NBATCH), N(2*NBATCH), K(2*NBATCH)
INTEGER(KIND=JPIM) :: LDA(2*NBATCH), LDB(2*NBATCH), LDC(2*NBATCH)
TYPE(C_PTR) :: A_PTRS(2*NBATCH), B_PTRS(2*NBATCH), C_PTRS(2*NBATCH)
REAL(KIND=JPRB), POINTER :: ZB_BUF(:,:), ZC_BUF(:,:)

ITHRESHOLD = S%ITHRESHOLD
NG = 0

IOFF_BA = 1
IOFF_C = 1
DO I = 1, NBATCH
  KMLOC = KMLOC_VALS(I)
  ILA = ILA_VALS(KMLOC)
  KIFC = KIFC_VALS(I)
  KDGLU = KDGLU_VALS(I)

  IF (ILA <= ITHRESHOLD .OR. .NOT. S%LUSEFLT) THEN
    NG = NG + 1
    M(NG) = KDGLU
    N(NG) = KIFC
    K(NG) = ILA
    LDA(NG) = KDGLU
    LDB(NG) = ILA
    LDC(NG) = KDGLU

    A_PTRS(NG) = RPNMA_PTRS(KMLOC)
    B_PTRS(NG) = C_LOC(ZWORK_BA(IOFF_BA))
    C_PTRS(NG) = C_LOC(ZWORK_CA(IOFF_C))
  ELSE
    CALL C_F_POINTER(C_LOC(ZWORK_BA(IOFF_BA)), ZB_BUF, [ILA, KIFC])
    CALL C_F_POINTER(C_LOC(ZWORK_CA(IOFF_C)),  ZC_BUF, [KDGLU, KIFC])
    CALL MULT_BUTM('N', S%FA(KMLOC)%YBUT_STRUCT_A, KIFC, ZB_BUF, ZC_BUF)
  ENDIF

  IOFF_BA = IOFF_BA + ILA * KIFC
  IOFF_C = IOFF_C + KDGLU * KIFC
ENDDO

IOFF_BS = 1
IOFF_C = 1
DO I = 1, NBATCH
  KMLOC = KMLOC_VALS(I)
  ILS = ILS_VALS(KMLOC)
  KIFC = KIFC_VALS(I)
  KDGLU = KDGLU_VALS(I)

  IF (ILS <= ITHRESHOLD .OR. .NOT. S%LUSEFLT) THEN
    NG = NG + 1
    M(NG) = KDGLU
    N(NG) = KIFC
    K(NG) = ILS
    LDA(NG) = KDGLU
    LDB(NG) = ILS
    LDC(NG) = KDGLU

    A_PTRS(NG) = RPNMS_PTRS(KMLOC)
    B_PTRS(NG) = C_LOC(ZWORK_BS(IOFF_BS))
    C_PTRS(NG) = C_LOC(ZWORK_CS(IOFF_C))
  ELSE
    CALL C_F_POINTER(C_LOC(ZWORK_BS(IOFF_BS)), ZB_BUF, [ILS, KIFC])
    CALL C_F_POINTER(C_LOC(ZWORK_CS(IOFF_C)),  ZC_BUF, [KDGLU, KIFC])
    CALL MULT_BUTM('N', S%FA(KMLOC)%YBUT_STRUCT_S, KIFC, ZB_BUF, ZC_BUF)
  ENDIF

  IOFF_BS = IOFF_BS + ILS * KIFC
  IOFF_C = IOFF_C + KDGLU * KIFC
ENDDO

IF (NG > 0) THEN
  CALL GEMM_BATCHED('N', 'N', M, N, K, 1.0_JPRB, 0.0_JPRB, &
      A_PTRS, LDA, B_PTRS, LDB, C_PTRS, LDC, NG)
ENDIF

END SUBROUTINE LEINV_BATCHED
END MODULE LEINV_BATCHED_MOD
