! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE LTDIR_CTLAD_BATCHED_CTL_MOD
USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

! Replace per-call ALLOCATE/DEALLOCATE of ZWORK_BA/BS/CA/CS with module-level SAVE 
! buffers that grow to the mem high-water mark across calls. First touch page faulting.
REAL(KIND=JPRB), ALLOCATABLE, TARGET, SAVE :: ZWORK_BA_PERSIST(:), ZWORK_BS_PERSIST(:)
REAL(KIND=JPRB), ALLOCATABLE, TARGET, SAVE :: ZWORK_CA_PERSIST(:), ZWORK_CS_PERSIST(:)

CONTAINS

SUBROUTINE ENSURE_PERSIST_BUFFER(BUF, INEED)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(INOUT) :: BUF(:)
INTEGER(KIND=JPIM), INTENT(IN) :: INEED
INTEGER(KIND=JPIM) :: J
IF (.NOT.ALLOCATED(BUF) .OR. INEED > SIZE(BUF)) THEN
  IF (ALLOCATED(BUF)) DEALLOCATE(BUF)
  ALLOCATE(BUF(INEED))
  !$OMP PARALLEL DO SCHEDULE(STATIC)
  DO J = 1, INEED
    BUF(J) = 0.0_JPRB
  ENDDO
  !$OMP END PARALLEL DO
ENDIF
END SUBROUTINE ENSURE_PERSIST_BUFFER

SUBROUTINE LTDIR_CTLAD(KF_FS, KF_UV, KF_SCALARS, &
    PSPVOR, PSPDIV, PSPSCALAR, &
    PSPSC3A, PSPSC3B, PSPSC2, &
    KFLDPTRUV, KFLDPTRSC)

USE PARKIND1,   ONLY : JPIM, JPRB
USE TPM_GEN,    ONLY : LALLOPERM
USE TPM_TRANS,  ONLY : FOUBUF, FOUBUF_IN
USE TPM_DISTR,  ONLY : D
USE TPM_FLT,    ONLY : S
USE TPM_FIELDS, ONLY : F
USE TPM_DIM,    ONLY : R
USE TPM_GEOMETRY, ONLY : G

USE PREPSNM_MOD, ONLY : PREPSNM
USE PRFI2AD_MOD, ONLY : PRFI2AD
USE LDFOU2_MOD, ONLY : LDFOU2
USE LEINV_BATCHED_MOD, ONLY : LEINV_BATCHED
USE UVTVDAD_MOD, ONLY : UVTVDAD
USE UPDSPAD_MOD, ONLY : UPDSPAD
USE TRMTOL_MOD, ONLY : TRMTOL
USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_LOC, C_PTR, C_F_POINTER

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KF_FS, KF_UV, KF_SCALARS
REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PSPVOR(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PSPDIV(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PSPSCALAR(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PSPSC3A(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PSPSC3B(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PSPSC2(:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KFLDPTRUV(:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KFLDPTRSC(:)

INTEGER(KIND=JPIM) :: JM, IM, IBLEN
INTEGER(KIND=JPIM) :: KM, KMLOC
INTEGER(KIND=JPIM) :: IFC, IIFC, IDGLU, ISL
INTEGER(KIND=JPIM) :: ILA, ILS, IA, IS, ISKIP
INTEGER(KIND=JPIM) :: IUS, IUE, IVS, IVE, IVORS, IVORE, IDIVS, IDIVE
INTEGER(KIND=JPIM) :: KLED2
INTEGER(KIND=JPIM) :: J, JK, JI, JGL, J1, JFLD, KDGLU
INTEGER(KIND=JPIM) :: NBATCH
INTEGER(KIND=JPIM) :: IOFF_BA, IOFF_BS, IOFF_CA, IOFF_CS
INTEGER(KIND=JPIM) :: IOFF

INTEGER(KIND=JPIM), ALLOCATABLE :: KFC_VALS(:), KIFC_VALS(:), KDGLU_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ILA_VALS(:), ILS_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ISKIP_VALS(:), ISL_VALS(:), KMLOC_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: IOFF_CA_VALS(:), IOFF_CS_VALS(:)
TYPE(C_PTR), ALLOCATABLE :: RPNMA_PTRS(:), RPNMS_PTRS(:)

REAL(KIND=JPRB), POINTER :: ZWORK_BA(:), ZWORK_BS(:)
REAL(KIND=JPRB), POINTER :: ZWORK_CA(:), ZWORK_CS(:)
REAL(KIND=JPRB), POINTER :: ZC_SECT(:,:)
REAL(KIND=JPRB) :: ZOA1(R%NLED4, MAX(1, 2*KF_FS))
REAL(KIND=JPRB) :: ZOA2(R%NLED4, MAX(4*KF_UV, 1))
REAL(KIND=JPRB) :: ZEPSNM(0:R%NTMAX+2)
REAL(KIND=JPRB), ALLOCATABLE :: ZAIA(:,:), ZSIA(:,:)

! ------------------------------------------------------------------

CALL GSTATS(105, 0)
IBLEN = D%NLENGT0B * 2 * KF_FS
IF (ALLOCATED(FOUBUF_IN)) THEN
  IF (MAX(1, IBLEN) > SIZE(FOUBUF_IN)) THEN
    DEALLOCATE(FOUBUF_IN)
    ALLOCATE(FOUBUF_IN(MAX(1, IBLEN)))
  ENDIF
ELSE
  ALLOCATE(FOUBUF_IN(MAX(1, IBLEN)))
ENDIF
IF (ALLOCATED(FOUBUF)) THEN
  IF (MAX(1, IBLEN) > SIZE(FOUBUF)) THEN
    DEALLOCATE(FOUBUF)
    ALLOCATE(FOUBUF(MAX(1, IBLEN)))
  ENDIF
ELSE
  ALLOCATE(FOUBUF(MAX(1, IBLEN)))
ENDIF

! ------------------------------------------------------------------

KLED2 = 2 * KF_FS

NBATCH = 0
DO JM = 1, D%NUMP
  IM = D%MYMS(JM)
  IDGLU = MIN(R%NDGNH, G%NDGLU(IM))
  IF (IDGLU > 0 .AND. 2*KF_FS > 0) NBATCH = NBATCH + 1
ENDDO

ALLOCATE(KFC_VALS(NBATCH), KIFC_VALS(NBATCH), KDGLU_VALS(NBATCH))
ALLOCATE(ILA_VALS(D%NUMP), ILS_VALS(D%NUMP))
ALLOCATE(ISKIP_VALS(D%NUMP), ISL_VALS(D%NUMP), KMLOC_VALS(NBATCH))
ALLOCATE(IOFF_CA_VALS(D%NUMP), IOFF_CS_VALS(D%NUMP))
ALLOCATE(RPNMA_PTRS(D%NUMP), RPNMS_PTRS(D%NUMP))

CALL GSTATS(1646, 0)

IF (KF_FS <= 0) THEN
  DEALLOCATE(KFC_VALS, KIFC_VALS, KDGLU_VALS)
  DEALLOCATE(ILA_VALS, ILS_VALS)
  DEALLOCATE(ISKIP_VALS, ISL_VALS, KMLOC_VALS)
  DEALLOCATE(IOFF_CA_VALS, IOFF_CS_VALS)
  DEALLOCATE(RPNMA_PTRS, RPNMS_PTRS)
  CALL GSTATS(1646, 1)
  GOTO 999
ENDIF

J = 0
IOFF_BA = 0
IOFF_BS = 0
IOFF_CA = 0
IOFF_CS = 0
DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  ISL_VALS(JM) = MAX(R%NDGNH - G%NDGLU(KM) + 1, 1)
  ILA_VALS(JM) = (R%NTMAX - KM + 2) / 2
  ILS_VALS(JM) = (R%NTMAX - KM + 3) / 2

  IF (KM == 0) THEN
    ISKIP_VALS(JM) = 2
  ELSE
    ISKIP_VALS(JM) = 1
  ENDIF

  IFC = 2 * KF_FS
  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2

  IOFF_CA_VALS(JM) = IOFF_CA + 1
  IOFF_CS_VALS(JM) = IOFF_CS + 1

  IF (IDGLU > 0) THEN
    J = J + 1
    KMLOC_VALS(J) = JM
    KFC_VALS(J) = IFC
    KIFC_VALS(J) = IIFC
    KDGLU_VALS(J) = IDGLU

    IOFF_BA = IOFF_BA + ILA_VALS(JM) * IIFC
    IOFF_BS = IOFF_BS + ILS_VALS(JM) * IIFC
    IOFF_CA = IOFF_CA + IDGLU * IIFC
    IOFF_CS = IOFF_CS + IDGLU * IIFC
  ENDIF

  RPNMA_PTRS(JM) = C_LOC(S%FA(JM)%RPNMA)
  RPNMS_PTRS(JM) = C_LOC(S%FA(JM)%RPNMS)
ENDDO

CALL ENSURE_PERSIST_BUFFER(ZWORK_BA_PERSIST, MAX(1, IOFF_BA))
CALL ENSURE_PERSIST_BUFFER(ZWORK_BS_PERSIST, MAX(1, IOFF_BS))
CALL ENSURE_PERSIST_BUFFER(ZWORK_CA_PERSIST, MAX(1, IOFF_CA))
CALL ENSURE_PERSIST_BUFFER(ZWORK_CS_PERSIST, MAX(1, IOFF_CS))
ZWORK_BA => ZWORK_BA_PERSIST
ZWORK_BS => ZWORK_BS_PERSIST
ZWORK_CA => ZWORK_CA_PERSIST
ZWORK_CS => ZWORK_CS_PERSIST

! ------------------------------------------------------------------

IOFF_BA = 1
IOFF_BS = 1
DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  KMLOC = JM
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  ISL = ISL_VALS(JM)
  ILA = ILA_VALS(JM)
  ILS = ILS_VALS(JM)
  IA = 1 + MOD(R%NTMAX - KM + 2, 2)
  IS = 1 + MOD(R%NTMAX - KM + 1, 2)
  ISKIP = ISKIP_VALS(JM)

  IFC = 2 * KF_FS
  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2

  IF (IDGLU <= 0) CYCLE

  CALL UPDSPAD(KM, KF_UV, KF_SCALARS, ZOA1, ZOA2, &
      PSPVOR, PSPDIV, PSPSCALAR, &
      PSPSC3A, PSPSC3B, PSPSC2, &
      KFLDPTRUV, KFLDPTRSC)

  IF (KF_UV > 0) THEN
    CALL PREPSNM(KM, KMLOC, ZEPSNM)
    IUS = 1
    IUE = 2 * KF_UV
    IVS = 2 * KF_UV + 1
    IVE = 4 * KF_UV
    IVORS = 1
    IVORE = 2 * KF_UV
    IDIVS = 2 * KF_UV + 1
    IDIVE = 4 * KF_UV
    ZOA1(:, IUS:IVE) = 0.0_JPRB
    CALL UVTVDAD(KM, KF_UV, ZEPSNM, ZOA1(:, IUS:IUE), ZOA1(:, IVS:IVE), &
        ZOA2(:, IVORS:IVORE), ZOA2(:, IDIVS:IDIVE))
  ENDIF

  DO JFLD = 1, IIFC
    JK = 1 + (JFLD - 1) * ISKIP
    ZWORK_BA(IOFF_BA:IOFF_BA+ILA-1) = ZOA1(IA:IA+(ILA-1)*2:2, JK)
    IOFF_BA = IOFF_BA + ILA
  ENDDO

  DO JFLD = 1, IIFC
    JK = 1 + (JFLD - 1) * ISKIP
    ZWORK_BS(IOFF_BS:IOFF_BS+ILS-1) = ZOA1(IS:IS+2*(ILS-1):2, JK)
    IOFF_BS = IOFF_BS + ILS
  ENDDO
ENDDO

! ------------------------------------------------------------------

IF (NBATCH > 0) THEN
  CALL LEINV_BATCHED(KF_FS, NBATCH, &
      KFC_VALS, KIFC_VALS, KDGLU_VALS, ILA_VALS, ILS_VALS, &
      ISKIP_VALS, ISL_VALS, KMLOC_VALS, &
      RPNMA_PTRS, RPNMS_PTRS, &
      ZWORK_BA, ZWORK_BS, ZWORK_CA, ZWORK_CS)
ENDIF

! ------------------------------------------------------------------

ALLOCATE(ZAIA(KLED2, R%NDGNH))
ALLOCATE(ZSIA(KLED2, R%NDGNH))

DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  KMLOC = JM
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  IF (IDGLU <= 0) CYCLE

  ISL = ISL_VALS(JM)
  ILA = ILA_VALS(JM)
  ILS = ILS_VALS(JM)
  IA = 1 + MOD(R%NTMAX - KM + 2, 2)
  IS = 1 + MOD(R%NTMAX - KM + 1, 2)
  ISKIP = ISKIP_VALS(JM)

  IFC = 2 * KF_FS
  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2
  KDGLU = IDGLU

  ZAIA(:, ISL:ISL+KDGLU-1) = 0.0_JPRB
  ZSIA(:, ISL:ISL+KDGLU-1) = 0.0_JPRB

  IF (KM == 0) THEN
    DO JGL = ISL, R%NDGNH
      DO J1 = 2, IFC, 2
        ZAIA(J1, JGL) = 0.0_JPRB
        ZSIA(J1, JGL) = 0.0_JPRB
      ENDDO
    ENDDO
  ENDIF

  IOFF = IOFF_CA_VALS(JM)
  CALL C_F_POINTER(C_LOC(ZWORK_CA(IOFF)), ZC_SECT, [KDGLU, IIFC])
  DO JFLD = 1, IIFC
    JK = 1 + (JFLD - 1) * ISKIP
    ZAIA(JK, ISL:ISL+KDGLU-1) = ZC_SECT(:, JFLD) * REAL(F%RW(ISL:ISL+KDGLU-1), JPRB)
  ENDDO

  IOFF = IOFF_CS_VALS(JM)
  CALL C_F_POINTER(C_LOC(ZWORK_CS(IOFF)), ZC_SECT, [KDGLU, IIFC])
  DO JFLD = 1, IIFC
    JK = 1 + (JFLD - 1) * ISKIP
    ZSIA(JK, ISL:ISL+KDGLU-1) = ZC_SECT(:, JFLD) * REAL(F%RW(ISL:ISL+KDGLU-1), JPRB)
  ENDDO

  CALL LDFOU2(KM, KF_UV, ZAIA, ZSIA)
  CALL PRFI2AD(KM, KMLOC, KF_FS, ZAIA, ZSIA)

ENDDO

DEALLOCATE(ZAIA, ZSIA)

CALL GSTATS(1646, 1)

! ------------------------------------------------------------------

CALL GSTATS(105, 1)

CALL GSTATS(181, 0)
CALL TRMTOL(FOUBUF, FOUBUF_IN, 2*KF_FS)
CALL GSTATS(181, 1)
IF (.NOT. LALLOPERM) DEALLOCATE(FOUBUF)

999 CONTINUE

NULLIFY(ZWORK_BA, ZWORK_BS, ZWORK_CA, ZWORK_CS)
DEALLOCATE(KFC_VALS, KIFC_VALS, KDGLU_VALS)
DEALLOCATE(ILA_VALS, ILS_VALS)
DEALLOCATE(ISKIP_VALS, ISL_VALS, KMLOC_VALS)
DEALLOCATE(IOFF_CA_VALS, IOFF_CS_VALS)
DEALLOCATE(RPNMA_PTRS, RPNMS_PTRS)

END SUBROUTINE LTDIR_CTLAD
END MODULE LTDIR_CTLAD_BATCHED_CTL_MOD
