! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE LTINV_BATCHED_CTL_MOD
USE PARKIND1, ONLY : JPIM, JPRB, JPRD

IMPLICIT NONE

REAL(KIND=JPRD), EXTERNAL :: TIMEF
REAL(KIND=JPRD), SAVE :: ZT_ACC_102B = 0.0_JPRD, ZT_ACC_1647B = 0.0_JPRD
REAL(KIND=JPRD), SAVE :: ZT_ACC_152B = 0.0_JPRD
INTEGER(KIND=JPIM), SAVE :: ZT_NCALLS_B = 0

! Replace per-call ALLOCATE/DEALLOCATE of ZWORK_BA/BS/CA/CS with module-level SAVE 
! buffers that grow to the mem high-water mark across calls. First touch page faulting.
REAL(KIND=JPRB), ALLOCATABLE, TARGET, SAVE :: ZWORK_BA_PERSIST(:), ZWORK_BS_PERSIST(:)
REAL(KIND=JPRB), ALLOCATABLE, TARGET, SAVE :: ZWORK_CA_PERSIST(:), ZWORK_CS_PERSIST(:)

CONTAINS

SUBROUTINE ENSURE_PERSIST_BUFFER(BUF, INEED)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(INOUT) :: BUF(:)
INTEGER(KIND=JPIM), INTENT(IN) :: INEED
INTEGER(KIND=JPIM) :: J
IF (.NOT.ALLOCATED(BUF) .OR. INEED > SIZE(BUF)) THEN
  IF (ALLOCATED(BUF)) DEALLOCATE(BUF)
  ALLOCATE(BUF(INEED))
  !$OMP PARALLEL DO SCHEDULE(STATIC)
  DO J = 1, INEED
    BUF(J) = 0.0_JPRB
  ENDDO
  !$OMP END PARALLEL DO
ENDIF
END SUBROUTINE ENSURE_PERSIST_BUFFER

SUBROUTINE LTINV_CTL(KF_OUT_LT, KF_UV, KF_SCALARS, KF_SCDERS, &
                     PSPVOR, PSPDIV, PSPSCALAR, &
                     PSPSC3A, PSPSC3B, PSPSC2, &
                     KFLDPTRUV, KFLDPTRSC, FSPGL_PROC)

USE PARKIND1,   ONLY : JPIM, JPRB
USE TPM_GEN,    ONLY : LALLOPERM
USE TPM_TRANS,  ONLY : FOUBUF, FOUBUF_IN, LDIVGP, LVORGP, NF_SC2, NF_SC3A, NF_SC3B, LATLON
USE TPM_DISTR,  ONLY : D, MYPROC
USE TPM_ECTRANS_OPTS, ONLY : LREPORT_STAGE_TIME
USE TPM_FLT,    ONLY : S
USE TPM_FIELDS, ONLY : F
USE TPM_DIM,    ONLY : R
USE TPM_GEOMETRY, ONLY : G

USE PREPSNM_MOD,     ONLY : PREPSNM
USE PRFI1B_MOD,      ONLY : PRFI1B
USE VDTUV_MOD,       ONLY : VDTUV
USE SPNSDE_MOD,      ONLY : SPNSDE
USE LEINV_BATCHED_MOD, ONLY : LEINV_BATCHED
USE ASRE1B_MOD,      ONLY : ASRE1B
USE FSPGL_INT_MOD,   ONLY : FSPGL_INT
USE ABORT_TRANS_MOD, ONLY : ABORT_TRANS
USE CDMAP_MOD,       ONLY : CDMAP
USE TRMTOL_MOD,      ONLY : TRMTOL
USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_LOC, C_PTR, C_F_POINTER

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KF_OUT_LT, KF_UV, KF_SCALARS, KF_SCDERS
REAL(KIND=JPRB), OPTIONAL, INTENT(IN)  :: PSPVOR(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN)  :: PSPDIV(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN)  :: PSPSCALAR(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN)  :: PSPSC3A(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN)  :: PSPSC3B(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN)  :: PSPSC2(:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KFLDPTRUV(:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KFLDPTRSC(:)
EXTERNAL  FSPGL_PROC
OPTIONAL  FSPGL_PROC

INTEGER(KIND=JPIM) :: JM, IM, IBLEN, IDIM1
INTEGER(KIND=JPIM) :: KM, KMLOC
INTEGER(KIND=JPIM) :: ISTA, IFC, IIFC, IDGLU, ISL, ISLO
INTEGER(KIND=JPIM) :: IFIRST, ILAST, IDIM3, J3
INTEGER(KIND=JPIM) :: IVORL, IVORU, IDIVL, IDIVU, IUL, IUU, IVL, IVU
INTEGER(KIND=JPIM) :: ISL2, ISU, IDL, IDU
INTEGER(KIND=JPIM) :: ILA, ILS, IA, IS, ISKIP
INTEGER(KIND=JPIM) :: KFC, KIFC, KDGLU
INTEGER(KIND=JPIM) :: J, JK, JI, JFN, IGLS, JGL, JFLD
INTEGER(KIND=JPIM) :: INSDS, INSDE, IUVS, IUVE, IST
INTEGER(KIND=JPIM) :: IOFF_BA, IOFF_BS, IOFF_C
INTEGER(KIND=JPIM) :: NBATCH, NLEI3, ILEI2
INTEGER(KIND=JPIM) :: IOFF
REAL(KIND=JPRB), ALLOCATABLE :: ZAOA1_LOC(:,:), ZSOA1_LOC(:,:)
REAL(KIND=JPRB), POINTER :: ZC_SECT(:,:)

INTEGER(KIND=JPIM), ALLOCATABLE :: KFC_VALS(:), KIFC_VALS(:), KDGLU_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ILA_VALS(:), ILS_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ISKIP_VALS(:), ISL_VALS(:), KMLOC_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: IOFF_BA_VALS(:), IOFF_BS_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: IOFF_C_VALS(:)
TYPE(C_PTR), ALLOCATABLE :: RPNMA_PTRS(:), RPNMS_PTRS(:)

REAL(KIND=JPRB), POINTER :: ZWORK_BA(:), ZWORK_BS(:), ZWORK_CA(:), ZWORK_CS(:)
REAL(KIND=JPRB), ALLOCATABLE :: ZALN(:,:)
! ZIA is per-thread 
REAL(KIND=JPRB), ALLOCATABLE :: ZIA(:,:)
REAL(KIND=JPRB) :: ZEPSNM(0:R%NTMAX+2)
REAL(KIND=JPRB) :: ZACTHE
REAL(KIND=JPRD) :: ZTW_102, ZTW_1647, ZTW_152

IF (LREPORT_STAGE_TIME) ZTW_102 = TIMEF()
CALL GSTATS(102, 0)

! ------------------------------------------------------------------

IDIM1 = 2*KF_OUT_LT
ILEI2 = 8*KF_UV + 2*KF_SCALARS + 2*KF_SCDERS
IBLEN = D%NLENGT0B * 2 * KF_OUT_LT

IF (ALLOCATED(FOUBUF)) THEN
  IF (MAX(1, IBLEN) > SIZE(FOUBUF)) THEN
    DEALLOCATE(FOUBUF)
    ALLOCATE(FOUBUF(MAX(1, IBLEN)))
  ENDIF
ELSE
  ALLOCATE(FOUBUF(MAX(1, IBLEN)))
ENDIF
IF (ALLOCATED(FOUBUF_IN)) THEN
  IF (MAX(1, IBLEN) > SIZE(FOUBUF_IN)) THEN
    DEALLOCATE(FOUBUF_IN)
    ALLOCATE(FOUBUF_IN(MAX(1, IBLEN)))
  ENDIF
ELSE
  ALLOCATE(FOUBUF_IN(MAX(1, IBLEN)))
  ! OMP-parallel first-touch zero
!$OMP PARALLEL DO SCHEDULE(STATIC)
  DO J=1,SIZE(FOUBUF_IN)
    FOUBUF_IN(J) = 0.0_JPRB
  ENDDO
!$OMP END PARALLEL DO
ENDIF

! ASRE1B doesn't write everywhere, so zero array in LDLL case
IF (S%LDLL) THEN
!$OMP PARALLEL DO SCHEDULE(STATIC)
  DO J=1,SIZE(FOUBUF_IN)
    FOUBUF_IN(J) = 0.0_JPRB
  ENDDO
!$OMP END PARALLEL DO
ENDIF

! ------------------------------------------------------------------
NLEI3 = R%NLEI3
IF (S%LDLL) THEN
  NLEI3 = 2 * R%NDGNH
ENDIF

NBATCH = 0
DO JM = 1, D%NUMP
  IM = D%MYMS(JM)
  IDGLU = MIN(R%NDGNH, G%NDGLU(IM))
  IF (IDGLU > 0) NBATCH = NBATCH + 1
ENDDO

ALLOCATE(KFC_VALS(NBATCH), KIFC_VALS(NBATCH), KDGLU_VALS(NBATCH))
ALLOCATE(ILA_VALS(D%NUMP), ILS_VALS(D%NUMP))
ALLOCATE(ISKIP_VALS(D%NUMP), ISL_VALS(D%NUMP), KMLOC_VALS(NBATCH))
ALLOCATE(IOFF_BA_VALS(D%NUMP), IOFF_BS_VALS(D%NUMP))
ALLOCATE(IOFF_C_VALS(D%NUMP))
ALLOCATE(RPNMA_PTRS(D%NUMP), RPNMS_PTRS(D%NUMP))

J = 0
IOFF_BA = 0
IOFF_BS = 0
IOFF_C = 0
DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  ISL_VALS(JM) = MAX(R%NDGNH - G%NDGLU(KM) + 1, 1)
  ILA_VALS(JM) = (R%NSMAX - KM + 2) / 2
  ILS_VALS(JM) = (R%NSMAX - KM + 3) / 2

  IF (KM == 0) THEN
    ISKIP_VALS(JM) = 2
  ELSE
    ISKIP_VALS(JM) = 1
  ENDIF

  IFC = 2 * KF_OUT_LT
  ISTA = 1
  IF (KF_UV > 0 .AND. .NOT. LVORGP) ISTA = ISTA + 2 * KF_UV
  IF (KF_UV > 0 .AND. .NOT. LDIVGP) ISTA = ISTA + 2 * KF_UV

  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2

  IOFF_C_VALS(JM) = IOFF_C + 1
  IOFF_BA_VALS(JM) = IOFF_BA + 1
  IOFF_BS_VALS(JM) = IOFF_BS + 1

  IF (IDGLU > 0) THEN
    J = J + 1
    KMLOC_VALS(J) = JM
    KFC_VALS(J) = IFC
    KIFC_VALS(J) = IIFC
    KDGLU_VALS(J) = IDGLU

    IOFF_BA = IOFF_BA + ILA_VALS(JM) * IIFC
    IOFF_BS = IOFF_BS + ILS_VALS(JM) * IIFC
    IOFF_C = IOFF_C + IDGLU * IIFC
  ENDIF

  ! Record Legendre matrix pointers
  RPNMA_PTRS(JM) = C_LOC(S%FA(JM)%RPNMA)
  RPNMS_PTRS(JM) = C_LOC(S%FA(JM)%RPNMS)
ENDDO

CALL ENSURE_PERSIST_BUFFER(ZWORK_BA_PERSIST, MAX(1, IOFF_BA))
CALL ENSURE_PERSIST_BUFFER(ZWORK_BS_PERSIST, MAX(1, IOFF_BS))
CALL ENSURE_PERSIST_BUFFER(ZWORK_CA_PERSIST, MAX(1, IOFF_C))
CALL ENSURE_PERSIST_BUFFER(ZWORK_CS_PERSIST, MAX(1, IOFF_C))
ZWORK_BA => ZWORK_BA_PERSIST
ZWORK_BS => ZWORK_BS_PERSIST
ZWORK_CA => ZWORK_CA_PERSIST
ZWORK_CS => ZWORK_CS_PERSIST

! ------------------------------------------------------------------
IF (LREPORT_STAGE_TIME) ZTW_1647 = TIMEF()
CALL GSTATS(1647, 0)

!$OMP PARALLEL DEFAULT(SHARED) &
!$OMP   PRIVATE(JM,KM,KMLOC,IDGLU,ISL,ILA,ILS,IA,IS,ISKIP,IFC,IIFC,ISTA, &
!$OMP           IFIRST,ILAST,IDIM3,J3,IVORL,IVORU,IDIVL,IDIVU, &
!$OMP           IUL,IUU,IVL,IVU,ISL2,ISU,IDL,IDU,JFN,JK,IOFF_BA,IOFF_BS, &
!$OMP           ZIA,ZEPSNM)
ALLOCATE(ZIA(R%NLEI1, MAX(1, ILEI2)))
!$OMP DO SCHEDULE(DYNAMIC,1)
DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  KMLOC = JM
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  IF (IDGLU <= 0) CYCLE

  ISL = ISL_VALS(JM)
  ILA = ILA_VALS(JM)
  ILS = ILS_VALS(JM)
  IA = 1 + MOD(R%NSMAX - KM + 2, 2)
  IS = 1 + MOD(R%NSMAX - KM + 1, 2)
  ISKIP = ISKIP_VALS(JM)

  IFC = 2 * KF_OUT_LT
  ISTA = 1
  IF (KF_UV > 0 .AND. .NOT. LVORGP) ISTA = ISTA + 2 * KF_UV
  IF (KF_UV > 0 .AND. .NOT. LDIVGP) ISTA = ISTA + 2 * KF_UV

  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2

  ! --- Per-wavenumber prep (same as LTINV) ---

  CALL PREPSNM(KM, KMLOC, ZEPSNM)

  IFIRST = 1
  ILAST = 4 * KF_UV

  IF (KF_UV > 0) THEN
    IVORL = 1
    IVORU = 2 * KF_UV
    IDIVL = 2 * KF_UV + 1
    IDIVU = 4 * KF_UV
    IUL = 4 * KF_UV + 1
    IUU = 6 * KF_UV
    IVL = 6 * KF_UV + 1
    IVU = 8 * KF_UV

    CALL PRFI1B(KM, ZIA(:, IVORL:IVORU), PSPVOR, KF_UV, KFLDPTRUV)
    CALL PRFI1B(KM, ZIA(:, IDIVL:IDIVU), PSPDIV, KF_UV, KFLDPTRUV)
    ILAST = ILAST + 4 * KF_UV

    CALL VDTUV(KM, KF_UV, ZEPSNM, ZIA(:, IVORL:IVORU), ZIA(:, IDIVL:IDIVU), &
        ZIA(:, IUL:IUU), ZIA(:, IVL:IVU))
  ENDIF

  IF (KF_SCALARS > 0) THEN
    IF (PRESENT(PSPSCALAR)) THEN
      IFIRST = ILAST + 1
      ILAST = IFIRST - 1 + 2 * KF_SCALARS
      CALL PRFI1B(KM, ZIA(:, IFIRST:ILAST), PSPSCALAR(:,:), KF_SCALARS, KFLDPTRSC)
    ELSE
      IF (PRESENT(PSPSC2) .AND. NF_SC2 > 0) THEN
        IFIRST = ILAST + 1
        ILAST = IFIRST - 1 + 2 * NF_SC2
        CALL PRFI1B(KM, ZIA(:, IFIRST:ILAST), PSPSC2(:,:), NF_SC2)
      ENDIF
      IF (PRESENT(PSPSC3A) .AND. NF_SC3A > 0) THEN
        IDIM3 = UBOUND(PSPSC3A, 3)
        DO J3 = 1, IDIM3
          IFIRST = ILAST + 1
          ILAST = IFIRST - 1 + 2 * NF_SC3A
          CALL PRFI1B(KM, ZIA(:, IFIRST:ILAST), PSPSC3A(:,:,J3), NF_SC3A)
        ENDDO
      ENDIF
      IF (PRESENT(PSPSC3B) .AND. NF_SC3B > 0) THEN
        IDIM3 = UBOUND(PSPSC3B, 3)
        DO J3 = 1, IDIM3
          IFIRST = ILAST + 1
          ILAST = IFIRST - 1 + 2 * NF_SC3B
          CALL PRFI1B(KM, ZIA(:, IFIRST:ILAST), PSPSC3B(:,:,J3), NF_SC3B)
        ENDDO
      ENDIF
    ENDIF
  ENDIF

      IF (KF_SCALARS > 0) THEN
    IF (ILAST /= 8*KF_UV+2*KF_SCALARS) THEN
      CALL ABORT_TRANS('LTINV_BATCHED_CTL: ILAST /= 8*KF_UV+2*KF_SCALARS')
    ENDIF
  ENDIF

  IF (KF_SCDERS > 0) THEN
    ISL2 = 2 * (4 * KF_UV) + 1
    ISU = ISL2 + 2 * KF_SCALARS - 1
    IDL = 2 * (4 * KF_UV + KF_SCALARS) + 1
    IDU = IDL + 2 * KF_SCDERS - 1
    CALL SPNSDE(KM, KF_SCALARS, ZEPSNM, ZIA(:, ISL2:ISU), ZIA(:, IDL:IDU))
  ENDIF

  IOFF_BA = IOFF_BA_VALS(JM)
  IOFF_BS = IOFF_BS_VALS(JM)

  ! Antisymmetric
  DO JFN = 1, IIFC
    JK = 1 + (JFN - 1) * ISKIP
    ZWORK_BA(IOFF_BA:IOFF_BA+ILA-1) = ZIA(IA+1:IA+1+(ILA-1)*2:2, ISTA + JK - 1)
    IOFF_BA = IOFF_BA + ILA
  ENDDO

  ! Symmetric
  DO JFN = 1, IIFC
    JK = 1 + (JFN - 1) * ISKIP
    ZWORK_BS(IOFF_BS:IOFF_BS+ILS-1) = ZIA(IS+1:IS+1+(ILS-1)*2:2, ISTA + JK - 1)
    IOFF_BS = IOFF_BS + ILS
  ENDDO

ENDDO
!$OMP END DO
DEALLOCATE(ZIA)
!$OMP END PARALLEL

! ------------------------------------------------------------------
! Phase 2: Batched GEMM('N','N')

IF (NBATCH > 0) THEN
  CALL LEINV_BATCHED(KF_OUT_LT, NBATCH, &
      KFC_VALS, KIFC_VALS, KDGLU_VALS, ILA_VALS, ILS_VALS, &
      ISKIP_VALS, ISL_VALS, KMLOC_VALS, &
      RPNMA_PTRS, RPNMS_PTRS, &
      ZWORK_BA, ZWORK_BS, ZWORK_CA, ZWORK_CS)
ENDIF

! ------------------------------------------------------------------

IF (LATLON .AND. S%LDLL) THEN
  !$OMP PARALLEL DEFAULT(SHARED) &
  !$OMP   PRIVATE(JM,KM,KMLOC,IDGLU,ISL,ISLO,KFC,KIFC,KDGLU,ISKIP,IOFF, &
  !$OMP           JFN,JK,JGL,IGLS,JFLD,IST,IUVS,IUVE,INSDS,INSDE,ZACTHE, &
  !$OMP           ZAOA1_LOC,ZSOA1_LOC,ZALN,ZEPSNM,ZC_SECT)
  ALLOCATE(ZAOA1_LOC(IDIM1, R%NDGNH))
  ALLOCATE(ZSOA1_LOC(IDIM1, R%NDGNH))
  ALLOCATE(ZALN(IDIM1, 2*R%NDGNH))
  !$OMP DO SCHEDULE(DYNAMIC,1)
  DO JM = 1, D%NUMP
    KM = D%MYMS(JM)
    KMLOC = JM
    IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
    IF (IDGLU <= 0) CYCLE

      ISL = ISL_VALS(JM)
      ISLO = S%FA(KMLOC)%ISLD
      KFC = 2 * KF_OUT_LT
      KIFC = KFC
      IF (KM == 0) KIFC = KFC / 2

    IF ((S%LSHIFTLL .AND. KM < 2*IDGLU) .OR. &
        (.NOT. S%LSHIFTLL .AND. KM < 2*(IDGLU-1))) THEN
      KDGLU = IDGLU
      ISKIP = ISKIP_VALS(JM)
      IOFF = IOFF_C_VALS(JM)

      ZAOA1_LOC(:, ISL:ISL+KDGLU-1) = 0.0_JPRB
      CALL C_F_POINTER(C_LOC(ZWORK_CA(IOFF)), ZC_SECT, [KDGLU, KIFC])
      DO JFN = 1, KIFC
        JK = 1 + (JFN - 1) * ISKIP
        ZAOA1_LOC(JK, ISL:ISL+KDGLU-1) = ZC_SECT(:, JFN)
      ENDDO

      ZSOA1_LOC(:, ISL:ISL+KDGLU-1) = 0.0_JPRB
      CALL C_F_POINTER(C_LOC(ZWORK_CS(IOFF)), ZC_SECT, [KDGLU, KIFC])
      DO JFN = 1, KIFC
        JK = 1 + (JFN - 1) * ISKIP
        ZSOA1_LOC(JK, ISL:ISL+KDGLU-1) = ZC_SECT(:, JFN)
      ENDDO
      DO JGL = ISL, R%NDGNH
        IGLS = 2 * R%NDGNH + 1 - JGL
        DO JFLD = 1, 2 * KF_OUT_LT
          ZALN(JFLD, JGL)  = ZSOA1_LOC(JFLD, JGL) + ZAOA1_LOC(JFLD, JGL)
          ZALN(JFLD, IGLS) = ZSOA1_LOC(JFLD, JGL) - ZAOA1_LOC(JFLD, JGL)
        ENDDO
      ENDDO

      IF (KF_UV > 0 .OR. KF_SCDERS > 0) THEN
        IST = 1
        IF (LVORGP) IST = IST + 2 * KF_UV
        IF (LDIVGP) IST = IST + 2 * KF_UV
        IUVS = IST
        IUVE = IST + 4 * KF_UV - 1
        IST = IST + 4 * KF_UV
        IST = IST + 2 * KF_SCALARS
        INSDS = IST
        INSDE = IST + 2 * KF_SCDERS - 1
        IGLS = 2 * R%NDGNH - ISL + 1
        IF (KF_UV > 0) THEN
          DO JGL = ISL, IGLS
            ZACTHE = REAL(F%RACTHE(JGL), JPRB)
            DO JFLD = IUVS, IUVE
              ZALN(JFLD, JGL) = ZALN(JFLD, JGL) * ZACTHE
            ENDDO
          ENDDO
        ENDIF
        IF (KF_SCDERS > 0) THEN
          DO JGL = ISL, IGLS
            ZACTHE = REAL(F%RACTHE(JGL), JPRB)
            DO JFLD = INSDS, INSDE
              ZALN(JFLD, JGL) = ZALN(JFLD, JGL) * ZACTHE
            ENDDO
          ENDDO
        ENDIF
      ENDIF

      CALL CDMAP(KM, KMLOC, ISL, ISLO, ZEPSNM(R%NTMAX+1), -1_JPIM, &
          R%NDGNH, S%NDGNHD, 2*KF_OUT_LT, ZALN, ZALN)
    ENDIF
  ENDDO
  !$OMP END DO
  DEALLOCATE(ZALN)
  DEALLOCATE(ZAOA1_LOC, ZSOA1_LOC)
  !$OMP END PARALLEL

ELSE
  !$OMP PARALLEL DEFAULT(SHARED) &
  !$OMP   PRIVATE(JM,KM,KMLOC,IDGLU,ISL,KFC,KIFC,KDGLU,ISKIP,IOFF, &
  !$OMP           JFN,JK,ZAOA1_LOC,ZSOA1_LOC,ZC_SECT)
  ALLOCATE(ZAOA1_LOC(IDIM1, R%NDGNH))
  ALLOCATE(ZSOA1_LOC(IDIM1, R%NDGNH))
  !$OMP DO SCHEDULE(DYNAMIC,1)
  DO JM = 1, D%NUMP
    KM = D%MYMS(JM)
    KMLOC = JM
    IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
    IF (IDGLU <= 0) CYCLE

    ISL = ISL_VALS(JM)
    KFC = 2 * KF_OUT_LT
    KIFC = KFC
    IF (KM == 0) KIFC = KFC / 2
    KDGLU = IDGLU
    ISKIP = ISKIP_VALS(JM)
    IOFF = IOFF_C_VALS(JM)

    ZAOA1_LOC(:, ISL:ISL+KDGLU-1) = 0.0_JPRB
    CALL C_F_POINTER(C_LOC(ZWORK_CA(IOFF)), ZC_SECT, [KDGLU, KIFC])
    DO JFN = 1, KIFC
      JK = 1 + (JFN - 1) * ISKIP
      ZAOA1_LOC(JK, ISL:ISL+KDGLU-1) = ZC_SECT(:, JFN)
    ENDDO

    ZSOA1_LOC(:, ISL:ISL+KDGLU-1) = 0.0_JPRB
    CALL C_F_POINTER(C_LOC(ZWORK_CS(IOFF)), ZC_SECT, [KDGLU, KIFC])
    DO JFN = 1, KIFC
      JK = 1 + (JFN - 1) * ISKIP
      ZSOA1_LOC(JK, ISL:ISL+KDGLU-1) = ZC_SECT(:, JFN)
    ENDDO

    CALL ASRE1B(KF_OUT_LT, KM, KMLOC, ZAOA1_LOC, ZSOA1_LOC)
  ENDDO
  !$OMP END DO
  DEALLOCATE(ZAOA1_LOC, ZSOA1_LOC)
  !$OMP END PARALLEL
ENDIF

IF (PRESENT(FSPGL_PROC)) THEN
  !$OMP PARALLEL DO DEFAULT(SHARED) SCHEDULE(DYNAMIC,1) PRIVATE(JM,KM,KMLOC)
  DO JM = 1, D%NUMP
    KM = D%MYMS(JM)
    KMLOC = JM
    CALL FSPGL_INT(KM, KMLOC, KF_UV, KF_SCALARS, KF_SCDERS, KF_OUT_LT, FSPGL_PROC, &
        KFLDPTRUV, KFLDPTRSC)
  ENDDO
  !$OMP END PARALLEL DO
ENDIF

CALL GSTATS(1647, 1)
IF (LREPORT_STAGE_TIME) ZT_ACC_1647B = ZT_ACC_1647B + (TIMEF() - ZTW_1647)

CALL GSTATS(102, 1)
IF (LREPORT_STAGE_TIME) ZT_ACC_102B = ZT_ACC_102B + (TIMEF() - ZTW_102)

! ------------------------------------------------------------------

IF (LREPORT_STAGE_TIME) ZTW_152 = TIMEF()
CALL GSTATS(152, 0)
CALL TRMTOL(FOUBUF_IN, FOUBUF, 2*KF_OUT_LT)
CALL GSTATS(152, 1)
IF (LREPORT_STAGE_TIME) THEN
  ZT_ACC_152B = ZT_ACC_152B + (TIMEF() - ZTW_152)
  ZT_NCALLS_B = ZT_NCALLS_B + 1
  IF (MYPROC == 1 .AND. ZT_NCALLS_B <= 10) THEN
    WRITE(0,'(A,F12.3,A,F12.3,A,F12.3)') 'LTINV_B wall: g102=', ZT_ACC_102B/ZT_NCALLS_B, &
     & 'g1647=', ZT_ACC_1647B/ZT_NCALLS_B, 'g152=', ZT_ACC_152B/ZT_NCALLS_B
  ENDIF
ENDIF
IF (.NOT. LALLOPERM) DEALLOCATE(FOUBUF_IN)

NULLIFY(ZWORK_BA, ZWORK_BS, ZWORK_CA, ZWORK_CS)
DEALLOCATE(KFC_VALS, KIFC_VALS, KDGLU_VALS)
DEALLOCATE(ILA_VALS, ILS_VALS)
DEALLOCATE(ISKIP_VALS, ISL_VALS, KMLOC_VALS)
DEALLOCATE(IOFF_BA_VALS, IOFF_BS_VALS)
DEALLOCATE(IOFF_C_VALS)
DEALLOCATE(RPNMA_PTRS, RPNMS_PTRS)

END SUBROUTINE LTINV_CTL
END MODULE LTINV_BATCHED_CTL_MOD
