! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE LTINV_CTLAD_BATCHED_CTL_MOD
USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

! Replace per-call ALLOCATE/DEALLOCATE of ZWORK_BA/BS/CA/CS with module-level SAVE 
! buffers that grow to the mem high-water mark across calls. First touch page faulting.
REAL(KIND=JPRB), ALLOCATABLE, TARGET, SAVE :: ZWORK_BA_PERSIST(:), ZWORK_BS_PERSIST(:)
REAL(KIND=JPRB), ALLOCATABLE, TARGET, SAVE :: ZWORK_CA_PERSIST(:), ZWORK_CS_PERSIST(:)

CONTAINS

SUBROUTINE ENSURE_PERSIST_BUFFER(BUF, INEED)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(INOUT) :: BUF(:)
INTEGER(KIND=JPIM), INTENT(IN) :: INEED
INTEGER(KIND=JPIM) :: J
IF (.NOT.ALLOCATED(BUF) .OR. INEED > SIZE(BUF)) THEN
  IF (ALLOCATED(BUF)) DEALLOCATE(BUF)
  ALLOCATE(BUF(INEED))
  !$OMP PARALLEL DO SCHEDULE(STATIC)
  DO J = 1, INEED
    BUF(J) = 0.0_JPRB
  ENDDO
  !$OMP END PARALLEL DO
ENDIF
END SUBROUTINE ENSURE_PERSIST_BUFFER

SUBROUTINE LTINV_CTLAD(KF_OUT_LT, KF_UV, KF_SCALARS, KF_SCDERS, &
    PSPVOR, PSPDIV, PSPSCALAR, &
    PSPSC3A, PSPSC3B, PSPSC2, &
    KFLDPTRUV, KFLDPTRSC)

USE PARKIND1,   ONLY : JPIM, JPRB
USE TPM_GEN,    ONLY : LALLOPERM
USE TPM_TRANS,  ONLY : FOUBUF, FOUBUF_IN, LDIVGP, LVORGP, NF_SC2, NF_SC3A, NF_SC3B
USE TPM_DISTR,  ONLY : D
USE TPM_FLT,    ONLY : S
USE TPM_FIELDS, ONLY : F
USE TPM_DIM,    ONLY : R
USE TPM_GEOMETRY, ONLY : G

USE PREPSNM_MOD, ONLY : PREPSNM
USE PRFI1BAD_MOD, ONLY : PRFI1BAD
USE VDTUVAD_MOD, ONLY : VDTUVAD
USE SPNSDEAD_MOD, ONLY : SPNSDEAD
USE LEINVAD_BATCHED_MOD, ONLY : LEINVAD_BATCHED
USE ASRE1BAD_MOD, ONLY : ASRE1BAD
USE ABORT_TRANS_MOD, ONLY : ABORT_TRANS
USE TRLTOM_MOD, ONLY : TRLTOM
USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_LOC, C_PTR, C_F_POINTER

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KF_OUT_LT, KF_UV, KF_SCALARS, KF_SCDERS
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT)  :: PSPVOR(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT)  :: PSPDIV(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT)  :: PSPSCALAR(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT)  :: PSPSC3A(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT)  :: PSPSC3B(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT)  :: PSPSC2(:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KFLDPTRUV(:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KFLDPTRSC(:)

INTEGER(KIND=JPIM) :: JM, IM, IBLEN, IDIM1
INTEGER(KIND=JPIM) :: KM, KMLOC
INTEGER(KIND=JPIM) :: ISTA, IFC, IIFC, IDGLU, ISL
INTEGER(KIND=JPIM) :: IFIRST, ILAST, IDIM3, J3
INTEGER(KIND=JPIM) :: IVORL, IVORU, IDIVL, IDIVU, IUL, IUU, IVL, IVU
INTEGER(KIND=JPIM) :: ISL2, ISU, IDL, IDU
INTEGER(KIND=JPIM) :: ILA, ILS, IA, IS, ISKIP
INTEGER(KIND=JPIM) :: J, JK, JI, JFN
INTEGER(KIND=JPIM) :: NBATCH, NLEI3, ILEI2
INTEGER(KIND=JPIM) :: IOFF_BA, IOFF_BS, IOFF_CA, IOFF_CS
INTEGER(KIND=JPIM) :: IOFF, KDGLU

INTEGER(KIND=JPIM), ALLOCATABLE :: KFC_VALS(:), KIFC_VALS(:), KDGLU_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ILA_VALS(:), ILS_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: ISKIP_VALS(:), ISL_VALS(:), KMLOC_VALS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: IOFF_CA_VALS(:), IOFF_CS_VALS(:)
TYPE(C_PTR), ALLOCATABLE :: RPNMA_PTRS(:), RPNMS_PTRS(:)

REAL(KIND=JPRB), POINTER :: ZWORK_BA(:), ZWORK_BS(:)
REAL(KIND=JPRB), POINTER :: ZWORK_CA(:), ZWORK_CS(:)
REAL(KIND=JPRB), POINTER :: ZC_SECT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZAOA1(:,:), ZSOA1(:,:)
REAL(KIND=JPRB) :: ZIA(R%NLEI1, MAX(1, 8*KF_UV+2*KF_SCALARS+2*KF_SCDERS))
REAL(KIND=JPRB) :: ZEPSNM(0:R%NTMAX+2)

! ------------------------------------------------------------------

IDIM1 = 2*KF_OUT_LT
ILEI2 = 8*KF_UV + 2*KF_SCALARS + 2*KF_SCDERS
IBLEN = D%NLENGT0B * 2 * KF_OUT_LT

IF (ALLOCATED(FOUBUF_IN)) THEN
  IF (MAX(1, IBLEN) > SIZE(FOUBUF_IN)) THEN
    DEALLOCATE(FOUBUF_IN)
    ALLOCATE(FOUBUF_IN(MAX(1, IBLEN)))
  ENDIF
ELSE
  ALLOCATE(FOUBUF_IN(MAX(1, IBLEN)))
ENDIF

CALL GSTATS(180,0)
CALL TRLTOM(FOUBUF, FOUBUF_IN, 2*KF_OUT_LT)
CALL GSTATS(180,1)
IF (.NOT. LALLOPERM) DEALLOCATE(FOUBUF)

! ------------------------------------------------------------------
CALL GSTATS(104, 0)


NBATCH = 0
DO JM = 1, D%NUMP
  IM = D%MYMS(JM)
  IDGLU = MIN(R%NDGNH, G%NDGLU(IM))
  IF (IDGLU > 0) NBATCH = NBATCH + 1
ENDDO

ALLOCATE(KFC_VALS(NBATCH), KIFC_VALS(NBATCH), KDGLU_VALS(NBATCH))
ALLOCATE(ILA_VALS(D%NUMP), ILS_VALS(D%NUMP))
ALLOCATE(ISKIP_VALS(D%NUMP), ISL_VALS(D%NUMP), KMLOC_VALS(NBATCH))
ALLOCATE(IOFF_CA_VALS(D%NUMP), IOFF_CS_VALS(D%NUMP))
ALLOCATE(RPNMA_PTRS(D%NUMP), RPNMS_PTRS(D%NUMP))

NLEI3 = R%NLEI3
IF (S%LDLL) THEN
  NLEI3 = 2 * R%NDGNH
ENDIF

IF (KF_OUT_LT <= 0) THEN
  DEALLOCATE(KFC_VALS, KIFC_VALS, KDGLU_VALS)
  DEALLOCATE(ILA_VALS, ILS_VALS)
  DEALLOCATE(ISKIP_VALS, ISL_VALS, KMLOC_VALS)
  DEALLOCATE(IOFF_CA_VALS, IOFF_CS_VALS)
  DEALLOCATE(RPNMA_PTRS, RPNMS_PTRS)
  RETURN
ENDIF

J = 0
IOFF_BA = 0
IOFF_BS = 0
IOFF_CA = 0
IOFF_CS = 0
DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  ISL_VALS(JM) = MAX(R%NDGNH - G%NDGLU(KM) + 1, 1)
  ILA_VALS(JM) = (R%NSMAX - KM + 2) / 2
  ILS_VALS(JM) = (R%NSMAX - KM + 3) / 2

  IF (KM == 0) THEN
    ISKIP_VALS(JM) = 2
  ELSE
    ISKIP_VALS(JM) = 1
  ENDIF

  IFC = 2 * KF_OUT_LT
  ISTA = 1
  IF (KF_UV > 0 .AND. .NOT. LVORGP) ISTA = ISTA + 2 * KF_UV
  IF (KF_UV > 0 .AND. .NOT. LDIVGP) ISTA = ISTA + 2 * KF_UV

  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2

  IOFF_CA_VALS(JM) = IOFF_CA + 1
  IOFF_CS_VALS(JM) = IOFF_CS + 1

  IF (IDGLU > 0) THEN
    J = J + 1
    KMLOC_VALS(J) = JM
    KFC_VALS(J) = IFC
    KIFC_VALS(J) = IIFC
    KDGLU_VALS(J) = IDGLU

    IOFF_BA = IOFF_BA + IDGLU * IIFC
    IOFF_BS = IOFF_BS + IDGLU * IIFC
    IOFF_CA = IOFF_CA + ILA_VALS(JM) * IIFC
    IOFF_CS = IOFF_CS + ILS_VALS(JM) * IIFC
  ENDIF

  RPNMA_PTRS(JM) = C_LOC(S%FA(JM)%RPNMA)
  RPNMS_PTRS(JM) = C_LOC(S%FA(JM)%RPNMS)
ENDDO

CALL ENSURE_PERSIST_BUFFER(ZWORK_BA_PERSIST, MAX(1, IOFF_BA))
CALL ENSURE_PERSIST_BUFFER(ZWORK_BS_PERSIST, MAX(1, IOFF_BS))
CALL ENSURE_PERSIST_BUFFER(ZWORK_CA_PERSIST, MAX(1, IOFF_CA))
CALL ENSURE_PERSIST_BUFFER(ZWORK_CS_PERSIST, MAX(1, IOFF_CS))
ZWORK_BA => ZWORK_BA_PERSIST
ZWORK_BS => ZWORK_BS_PERSIST
ZWORK_CA => ZWORK_CA_PERSIST
ZWORK_CS => ZWORK_CS_PERSIST

! ------------------------------------------------------------------

CALL GSTATS(1648, 0)

NLEI3 = R%NLEI3
IF (S%LDLL) THEN
  NLEI3 = 2 * R%NDGNH
ENDIF

ALLOCATE(ZAOA1(IDIM1, NLEI3))
ALLOCATE(ZSOA1(IDIM1, NLEI3))

IOFF_BA = 1
IOFF_BS = 1
DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  KMLOC = JM
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  ISL = ISL_VALS(JM)
  ILA = ILA_VALS(JM)
  ILS = ILS_VALS(JM)
  IA = 1 + MOD(R%NSMAX - KM + 2, 2)
  IS = 1 + MOD(R%NSMAX - KM + 1, 2)
  ISKIP = ISKIP_VALS(JM)

  IFC = 2 * KF_OUT_LT
  ISTA = 1
  IF (KF_UV > 0 .AND. .NOT. LVORGP) ISTA = ISTA + 2 * KF_UV
  IF (KF_UV > 0 .AND. .NOT. LDIVGP) ISTA = ISTA + 2 * KF_UV

  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2

  IF (IDGLU <= 0) CYCLE

  CALL ASRE1BAD(KF_OUT_LT, KM, KMLOC, ZAOA1, ZSOA1)

  DO JFN = 1, IIFC
    JK = 1 + (JFN - 1) * ISKIP
    ZWORK_BA(IOFF_BA:IOFF_BA+IDGLU-1) = ZAOA1(JK, ISL:ISL+IDGLU-1)
    IOFF_BA = IOFF_BA + IDGLU
  ENDDO

  DO JFN = 1, IIFC
    JK = 1 + (JFN - 1) * ISKIP
    ZWORK_BS(IOFF_BS:IOFF_BS+IDGLU-1) = ZSOA1(JK, ISL:ISL+IDGLU-1)
    IOFF_BS = IOFF_BS + IDGLU
  ENDDO
ENDDO

DEALLOCATE(ZAOA1, ZSOA1)

! ------------------------------------------------------------------

IF (NBATCH > 0) THEN
  CALL LEINVAD_BATCHED(KF_OUT_LT, NBATCH, &
      KFC_VALS, KIFC_VALS, KDGLU_VALS, ILA_VALS, ILS_VALS, &
      ISKIP_VALS, ISL_VALS, KMLOC_VALS, &
      RPNMA_PTRS, RPNMS_PTRS, &
      ZWORK_BA, ZWORK_BS, ZWORK_CA, ZWORK_CS)
ENDIF

! ------------------------------------------------------------------

DO JM = 1, D%NUMP
  KM = D%MYMS(JM)
  KMLOC = JM
  IDGLU = MIN(R%NDGNH, G%NDGLU(KM))
  IF (IDGLU <= 0) CYCLE

  ISL = ISL_VALS(JM)
  ILA = ILA_VALS(JM)
  ILS = ILS_VALS(JM)
  IA = 1 + MOD(R%NSMAX - KM + 2, 2)
  IS = 1 + MOD(R%NSMAX - KM + 1, 2)
  ISKIP = ISKIP_VALS(JM)

  IFC = 2 * KF_OUT_LT
  ISTA = 1
  IF (KF_UV > 0 .AND. .NOT. LVORGP) ISTA = ISTA + 2 * KF_UV
  IF (KF_UV > 0 .AND. .NOT. LDIVGP) ISTA = ISTA + 2 * KF_UV

  IIFC = IFC
  IF (KM == 0) IIFC = IFC / 2
  KDGLU = IDGLU

  CALL PREPSNM(KM, KMLOC, ZEPSNM)

  ZIA(:, ISTA:ISTA+IFC-1) = 0.0_JPRB


  IOFF = IOFF_CA_VALS(JM)
  CALL C_F_POINTER(C_LOC(ZWORK_CA(IOFF)), ZC_SECT, [ILA, IIFC])
  DO JFN = 1, IIFC
    JK = 1 + (JFN - 1) * ISKIP
    ZIA(IA+1:IA+1+(ILA-1)*2:2, ISTA + JK - 1) = ZC_SECT(:, JFN)
  ENDDO

  IOFF = IOFF_CS_VALS(JM)
  CALL C_F_POINTER(C_LOC(ZWORK_CS(IOFF)), ZC_SECT, [ILS, IIFC])
  DO JFN = 1, IIFC
    JK = 1 + (JFN - 1) * ISKIP
    ZIA(IS+1:IS+1+(ILS-1)*2:2, ISTA + JK - 1) = ZC_SECT(:, JFN)
  ENDDO

  ZIA(:, 1:ISTA-1) = 0.0_JPRB

  IFIRST = 1
  ILAST = 4 * KF_UV

  IF (KF_UV > 0) THEN
    IVORL = 1
    IVORU = 2 * KF_UV
    IDIVL = 2 * KF_UV + 1
    IDIVU = 4 * KF_UV
    IUL = 4 * KF_UV + 1
    IUU = 6 * KF_UV
    IVL = 6 * KF_UV + 1
    IVU = 8 * KF_UV

    CALL VDTUVAD(KM, KF_UV, ZEPSNM, ZIA(:, IVORL:IVORU), ZIA(:, IDIVL:IDIVU), &
        ZIA(:, IUL:IUU), ZIA(:, IVL:IVU))
    CALL PRFI1BAD(KM, ZIA(:, IVORL:IVORU), PSPVOR, KF_UV, KFLDPTRUV)
    CALL PRFI1BAD(KM, ZIA(:, IDIVL:IDIVU), PSPDIV, KF_UV, KFLDPTRUV)
    ILAST = ILAST + 4 * KF_UV
  ENDIF

  IF (KF_SCDERS > 0) THEN
    ISL2 = 2 * (4 * KF_UV) + 1
    ISU = ISL2 + 2 * KF_SCALARS - 1
    IDL = 2 * (4 * KF_UV + KF_SCALARS) + 1
    IDU = IDL + 2 * KF_SCDERS - 1
    CALL SPNSDEAD(KM, KF_SCALARS, ZEPSNM, ZIA(:, ISL2:ISU), ZIA(:, IDL:IDU))
  ENDIF

  IF (KF_SCALARS > 0) THEN
    IF (PRESENT(PSPSCALAR)) THEN
      IFIRST = ILAST + 1
      ILAST = IFIRST - 1 + 2 * KF_SCALARS
      CALL PRFI1BAD(KM, ZIA(:, IFIRST:ILAST), PSPSCALAR(:,:), KF_SCALARS, KFLDPTRSC)
    ELSE
      IF (PRESENT(PSPSC2) .AND. NF_SC2 > 0) THEN
        IFIRST = ILAST + 1
        ILAST = IFIRST - 1 + 2 * NF_SC2
        CALL PRFI1BAD(KM, ZIA(:, IFIRST:ILAST), PSPSC2(:,:), NF_SC2)
      ENDIF
      IF (PRESENT(PSPSC3A) .AND. NF_SC3A > 0) THEN
        IDIM3 = UBOUND(PSPSC3A, 3)
        DO J3 = 1, IDIM3
          IFIRST = ILAST + 1
          ILAST = IFIRST - 1 + 2 * NF_SC3A
          CALL PRFI1BAD(KM, ZIA(:, IFIRST:ILAST), PSPSC3A(:,:,J3), NF_SC3A)
        ENDDO
      ENDIF
      IF (PRESENT(PSPSC3B) .AND. NF_SC3B > 0) THEN
        IDIM3 = UBOUND(PSPSC3B, 3)
        DO J3 = 1, IDIM3
          IFIRST = ILAST + 1
          ILAST = IFIRST - 1 + 2 * NF_SC3B
          CALL PRFI1BAD(KM, ZIA(:, IFIRST:ILAST), PSPSC3B(:,:,J3), NF_SC3B)
        ENDDO
      ENDIF
    ENDIF
  ENDIF

  IF (KF_SCALARS > 0) THEN
    IF (ILAST /= 8*KF_UV+2*KF_SCALARS) THEN
      CALL ABORT_TRANS('LTINV_CTLAD_BATCHED_CTL: ILAST /= 8*KF_UV+2*KF_SCALARS')
    ENDIF
  ENDIF
ENDDO

CALL GSTATS(1648, 1)

IF (.NOT. LALLOPERM) DEALLOCATE(FOUBUF_IN)
CALL GSTATS(104, 1)

NULLIFY(ZWORK_BA, ZWORK_BS, ZWORK_CA, ZWORK_CS)
DEALLOCATE(KFC_VALS, KIFC_VALS, KDGLU_VALS)
DEALLOCATE(ILA_VALS, ILS_VALS)
DEALLOCATE(ISKIP_VALS, ISL_VALS, KMLOC_VALS)
DEALLOCATE(IOFF_CA_VALS, IOFF_CS_VALS)
DEALLOCATE(RPNMA_PTRS, RPNMS_PTRS)

END SUBROUTINE LTINV_CTLAD
END MODULE LTINV_CTLAD_BATCHED_CTL_MOD
