! (C) Copyright 2000- ECMWF.
! (C) Copyright 2000- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TPM_FFTW
!   Author.
!   -------
!     George Mozdzynski
!
!   Modifications.
!   -------------- 
!     Original      October 2014
!     R. El Khatib 01-Sep-2015 More subroutines for better modularity
!        R. El Khatib  08-Jun-2023 LALL_FFTW for better flexibility

USE, INTRINSIC :: ISO_C_BINDING

USE PARKIND1   ,ONLY : JPIB, JPIM, JPRB, JPRD
USE MPL_MODULE ,ONLY : MPL_MYRANK, MPL_RANK, MPL_NUMPROC, &
  & MPL_ALLGATHERV, MPL_GATHERV
USE YOMHOOK    ,ONLY : LHOOK, DR_HOOK, JPHOOK
USE OMP_LIB    ,ONLY : OMP_GET_MAX_THREADS, OMP_GET_THREAD_NUM

IMPLICIT NONE

SAVE

#ifdef __NEC__
! From NLC (NEC Numeric Library Collection)
#include "aslfftw3.f03"
#define FFTW_NO_SIMD 0
#else
#include "fftw3.f03"
#endif

PRIVATE
PUBLIC CREATE_PLAN_FFTW, DESTROY_PLAN_FFTW, DESTROY_PLANS_FFTW, INIT_PLANS_FFTW, &
      & FFTW_RESOL, TW, EXEC_FFTW, EXEC_EFFTW

TYPE FFTW_TYPE
  INTEGER(KIND=JPIM),ALLOCATABLE :: N_PLANS(:)
  TYPE(FFTW_PLAN),POINTER :: FFTW_PLANS(:) => NULL()
  INTEGER(KIND=JPIM) :: N_MAX=0         ! maximum number of latitudes
  INTEGER(KIND=JPIM) :: N_MAX_PLANS=4   ! maximum number of plans for each active latitude
  LOGICAL            :: LALL_FFTW=.FALSE. ! T=do kfields ffts in one batch, F=do kfields ffts one at a time
END TYPE FFTW_TYPE


TYPE FFTW_PLAN
  INTEGER(KIND=JPIM) :: NPLAN_ID=123456
  INTEGER(KIND=JPIB) :: NPLAN
  INTEGER(KIND=JPIM) :: NLOT
  INTEGER(KIND=JPIM) :: NTYPE
  TYPE(FFTW_PLAN),POINTER :: NEXT_PLAN => NULL()
END TYPE FFTW_PLAN

TYPE(FFTW_TYPE),ALLOCATABLE,TARGET :: FFTW_RESOL(:)
TYPE(FFTW_TYPE),POINTER     :: TW

! per-thread persistent FFTW scratch buffers, allocated once in INIT_PLANS_FFTW, grows 
! on demand in ENSURE_FFT_BUFFER, and freed in DESTROY_PLANS_FFTW
! Replaces per-call FFTW_ALLOC_COMPLEX/FFTW_FREE in EXEC_FFTW / EXEC_EFFTW
TYPE(C_PTR),       ALLOCATABLE, SAVE :: ZFFT_PERSIST_PTRS(:)
INTEGER(C_SIZE_T), ALLOCATABLE, SAVE :: ZFFT_PERSIST_CAPS(:)

! FFTW planning + wisdom storing. Controlled with ECTRANS_FFTW_WISDOM environment variable:
!   * CREATE_PLAN_FFTW uses FFTW_MEASURE (very slow first time-step in initial run, faster ffts subsequently)
!   * INIT_PLANS_FFTW imports wisdom from <ECTRANS_FFTW_WISDOM>.{dp,sp} it file is present
!   * DESTROY_PLANS_FFTW exports same <ECTRANS_FFTW_WISDOM>.{dp,sp} file
!   * Bit reproducibility is obtained if wisdom file doesn't change between runs 
!   * EXEC_FFTW / EXEC_EFFTW use a hoisted ZINV = 1/KRLEN reciprocal-
!     multiply in the output scale loop (last-bit different from the
!     division form, but reproducible).
! Default (and unset ECTRANS_FFTW_WISDOM) behaviour: FFTW_ESTIMATE+FFTW_NO_SIMD, no wisdom I/O,
LOGICAL, SAVE :: LUSE_MEASURE     = .FALSE.
LOGICAL, SAVE :: LWISDOM_IMPORTED = .FALSE.

! libc free() for releasing the malloc'd string returned by
! fftw{,f}_export_wisdom_to_string
INTERFACE
  SUBROUTINE C_FREE(PTR) BIND(C, NAME='free')
    IMPORT :: C_PTR
    TYPE(C_PTR), VALUE :: PTR
  END SUBROUTINE C_FREE
END INTERFACE



! ------------------------------------------------------------------
CONTAINS
! ------------------------------------------------------------------


SUBROUTINE WISDOM_FILENAME(CDPATH, KSTAT)
CHARACTER(LEN=:), ALLOCATABLE, INTENT(OUT) :: CDPATH
INTEGER(KIND=JPIM),            INTENT(OUT) :: KSTAT
CHARACTER(LEN=4096) :: ZBUF
INTEGER :: ILEN, ISTAT

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_FFTW_WISDOM', VALUE=ZBUF, &
  & LENGTH=ILEN, STATUS=ISTAT)
IF (ISTAT /= 0 .OR. ILEN == 0 .OR. ILEN > LEN(ZBUF)) THEN
  KSTAT = 1
  RETURN
ENDIF
IF (JPRB == JPRD) THEN
  CDPATH = ZBUF(1:ILEN) // '.dp'
ELSE
  CDPATH = ZBUF(1:ILEN) // '.sp'
ENDIF
KSTAT = 0
END SUBROUTINE WISDOM_FILENAME


! Convert a Fortran character string to a contiguous, NUL-terminated
! CHARACTER(KIND=C_CHAR) array compatible with `const char *filename`
SUBROUTINE STR_TO_CSTR(CDIN, CDOUT)
CHARACTER(LEN=*),                    INTENT(IN)  :: CDIN
CHARACTER(KIND=C_CHAR), ALLOCATABLE, INTENT(OUT) :: CDOUT(:)
INTEGER(KIND=JPIM) :: IL, J
IL = LEN_TRIM(CDIN)
ALLOCATE(CDOUT(IL+1))
DO J = 1, IL
  CDOUT(J) = CDIN(J:J)
END DO
CDOUT(IL+1) = C_NULL_CHAR
END SUBROUTINE STR_TO_CSTR


! Import FFTW wisdom from <ECTRANS_FFTW_WISDOM>.{dp,sp}. All ranks
! read the file.
SUBROUTINE IMPORT_FFTW_WISDOM
CHARACTER(LEN=:),       ALLOCATABLE :: ZPATH
CHARACTER(KIND=C_CHAR), ALLOCATABLE :: ZCPATH(:)
INTEGER(KIND=JPIM) :: ISTAT
INTEGER(C_INT)     :: IRET
LOGICAL            :: LLPRINT

IF (LWISDOM_IMPORTED) RETURN
CALL WISDOM_FILENAME(ZPATH, ISTAT)
IF (ISTAT /= 0) RETURN
CALL STR_TO_CSTR(ZPATH, ZCPATH)

IF (JPRB == JPRD) THEN
  IRET = FFTW_IMPORT_WISDOM_FROM_FILENAME(ZCPATH)
ELSE
  IRET = FFTWF_IMPORT_WISDOM_FROM_FILENAME(ZCPATH)
ENDIF
! Mark imported even on failure: missing/malformed file should not be
! retried on subsequent resolution setups.
LWISDOM_IMPORTED = .TRUE.
LLPRINT = (MPL_NUMPROC < 1) .OR. (MPL_RANK == 1)
IF (LLPRINT) THEN
  IF (IRET == 1) THEN
    WRITE(0,'(A,A)') 'TPM_FFTW: imported FFTW wisdom from ', TRIM(ZPATH)
  ELSE
    WRITE(0,'(A,A,A)') &
      & 'TPM_FFTW: WARNING failed to import FFTW wisdom from ', &
      & TRIM(ZPATH), ' (continuing with empty wisdom)'
  ENDIF
ENDIF
END SUBROUTINE IMPORT_FFTW_WISDOM


! Export FFTW wisdom to <ECTRANS_FFTW_WISDOM>.{dp,sp}.
!
! In MPI runs each rank only measures plans for its own set
! of latitudes, so rank 1's wisdom is insufficient. 
! Gather every rank's wisdom string to rank 1, import them with rank 1
! (FFTW wisdom is additive), and then export to disk from rank 1.
! MPL_GATHER remains manageable (5MB for tco639 on 32 ranks) and scales
! linearly with NPROC
SUBROUTINE EXPORT_FFTW_WISDOM
CHARACTER(LEN=:),       ALLOCATABLE :: ZPATH
CHARACTER(KIND=C_CHAR), ALLOCATABLE :: ZCPATH(:)
CHARACTER(KIND=C_CHAR), POINTER     :: ZLOC(:)
CHARACTER(KIND=C_CHAR), ALLOCATABLE, TARGET :: ZRANK(:)
INTEGER(KIND=JPIM),     ALLOCATABLE :: IBUF_LOC(:), IBUF_ALL(:)
INTEGER(KIND=JPIM),     ALLOCATABLE :: ILENS(:), IWORDS(:), IDISPLS(:), IONES(:)
INTEGER(KIND=JPIM) :: ISTAT, ILEN_LOC, IWORDS_LOC, ITOT_WORDS
INTEGER(KIND=JPIM) :: JR, JJ, IHUGE, IWORD, IBPOS, IBYTE
INTEGER(KIND=JPIM) :: IOFF, IL
INTEGER(C_INT)     :: IRET
TYPE(C_PTR)        :: IPTR
LOGICAL            :: LLROOT, LLMPI
! Dense byte packing: 4 bytes per JPIM word (previously 1 byte per JPIM).
! Cuts the gather payload by 4x, giving 4x more headroom before ITOT_WORDS
! or the MPI count/displ arguments (INTEGER(JPIM)) overflow at large
! NPROC. The remaining O(NPROC) scaling is addressed in a follow-up
! commit (hierarchical union reduction).
INTEGER(KIND=JPIM), PARAMETER :: IBPW = 4  ! bytes per JPIM word

! this does nothing if ECTRANS_FFTW_WISDOM environment variable not set
CALL WISDOM_FILENAME(ZPATH, ISTAT)
IF (ISTAT /= 0) RETURN

LLMPI  = (MPL_NUMPROC >= 1)
LLROOT = (.NOT. LLMPI) .OR. (MPL_RANK == 1)

! every rank exports its own wisdom to an in-memory C string.
! FFTW returns a malloc'd, NUL-terminated buffer that needs to be freed
IF (JPRB == JPRD) THEN
  IPTR = FFTW_EXPORT_WISDOM_TO_STRING()
ELSE
  IPTR = FFTWF_EXPORT_WISDOM_TO_STRING()
ENDIF

! Determine the length by scanning to the NUL terminator
ILEN_LOC = 0
IF (C_ASSOCIATED(IPTR)) THEN
  IHUGE = 16 * 1024 * 1024 !! 16 MB ... generous :) 
  CALL C_F_POINTER(IPTR, ZLOC, [IHUGE])
  DO JJ = 1, IHUGE
    IF (ZLOC(JJ) == C_NULL_CHAR) EXIT
    ILEN_LOC = ILEN_LOC + 1
  ENDDO
ENDIF

! Pack bytes densely into JPIM words: 4 bytes/word, little-endian.
! Padding beyond ILEN_LOC is zero-initialised. IBPW-byte round-up is
! safe because the receiver uses ILENS(JR) (byte count) to bound the
! unpack loop.
IWORDS_LOC = (ILEN_LOC + IBPW - 1) / IBPW
ALLOCATE(IBUF_LOC(MAX(IWORDS_LOC, 1)))
IBUF_LOC(:) = 0
DO JJ = 1, ILEN_LOC
  IWORD = (JJ - 1) / IBPW + 1
  IBPOS = MOD(JJ - 1, IBPW)
  IBUF_LOC(IWORD) = IOR(IBUF_LOC(IWORD), &
    & ISHFT(IAND(ICHAR(ZLOC(JJ)), 255), 8 * IBPOS))
ENDDO

! clean up malloc'd FFTW string
IF (C_ASSOCIATED(IPTR)) CALL C_FREE(IPTR)
NULLIFY(ZLOC)

IF (LLMPI) THEN
  ! Gather per-rank byte lengths so rank 1 can size its receive buffer
  ! and every rank can compute word-count displacements.
  ALLOCATE(ILENS(MPL_NUMPROC))
  ALLOCATE(IONES(MPL_NUMPROC))
  IONES(:) = 1
  CALL MPL_ALLGATHERV([ILEN_LOC], ILENS, IONES, KSENDCOUNT=1, &
    & CDSTRING='TPM_FFTW:EXPORT_WISDOM:LENS')
  DEALLOCATE(IONES)

  ! Word counts and displacements for the packed payload.
  ALLOCATE(IWORDS(MPL_NUMPROC))
  ALLOCATE(IDISPLS(MPL_NUMPROC))
  DO JR = 1, MPL_NUMPROC
    IWORDS(JR) = (ILENS(JR) + IBPW - 1) / IBPW
  ENDDO
  IDISPLS(1) = 0
  DO JR = 2, MPL_NUMPROC
    IDISPLS(JR) = IDISPLS(JR-1) + IWORDS(JR-1)
  ENDDO
  ITOT_WORDS = IDISPLS(MPL_NUMPROC) + IWORDS(MPL_NUMPROC)

  ! gather the packed wisdom to rank 1
  IF (LLROOT) THEN
    ALLOCATE(IBUF_ALL(MAX(ITOT_WORDS, 1)))
    IBUF_ALL(:) = 0
    CALL MPL_GATHERV(IBUF_LOC(1:IWORDS_LOC), KROOT=1, KRECVBUF=IBUF_ALL, &
      & KRECVCOUNTS=IWORDS, KSENDCOUNT=IWORDS_LOC, KRECVDISPL=IDISPLS, &
      & CDSTRING='TPM_FFTW:EXPORT_WISDOM')
  ELSE
    ALLOCATE(IBUF_ALL(1))
    CALL MPL_GATHERV(IBUF_LOC(1:IWORDS_LOC), KROOT=1, &
      & KSENDCOUNT=IWORDS_LOC, &
      & CDSTRING='TPM_FFTW:EXPORT_WISDOM')
    DEALLOCATE(IBUF_ALL)
  ENDIF
ENDIF

DEALLOCATE(IBUF_LOC)

! Unpack each rank's wisdom (bytes recovered from packed words) and
! import into rank 1's planner
IF (LLROOT) THEN
  IF (LLMPI) THEN
    DO JR = 1, MPL_NUMPROC
      IF (JR == 1) CYCLE          ! rank 1's wisdom
      IL = ILENS(JR)
      IF (IL <= 0) CYCLE
      IOFF = IDISPLS(JR)          ! word offset into IBUF_ALL
      ALLOCATE(ZRANK(IL + 1))
      DO JJ = 1, IL
        IWORD = (JJ - 1) / IBPW + 1
        IBPOS = MOD(JJ - 1, IBPW)
        IBYTE = IAND(ISHFT(IBUF_ALL(IOFF + IWORD), -8 * IBPOS), 255)
        ZRANK(JJ) = ACHAR(IBYTE)
      ENDDO
      ZRANK(IL + 1) = C_NULL_CHAR
      IF (JPRB == JPRD) THEN
        IRET = FFTW_IMPORT_WISDOM_FROM_STRING(ZRANK)
      ELSE
        IRET = FFTWF_IMPORT_WISDOM_FROM_STRING(ZRANK)
      ENDIF
      IF (IRET /= 1) THEN
        WRITE(0,'(A,I6)') 'TPM_FFTW: WARNING failed to merge wisdom from rank ', JR
      ENDIF
      DEALLOCATE(ZRANK)
    ENDDO
    DEALLOCATE(IBUF_ALL)
    DEALLOCATE(ILENS)
    DEALLOCATE(IWORDS)
    DEALLOCATE(IDISPLS)
  ENDIF

  CALL STR_TO_CSTR(ZPATH, ZCPATH)
  IF (JPRB == JPRD) THEN
    IRET = FFTW_EXPORT_WISDOM_TO_FILENAME(ZCPATH)
  ELSE
    IRET = FFTWF_EXPORT_WISDOM_TO_FILENAME(ZCPATH)
  ENDIF
  IF (IRET == 1) THEN
    WRITE(0,'(A,A)') 'TPM_FFTW: exported unified FFTW wisdom to ', TRIM(ZPATH)
  ELSE
    WRITE(0,'(A,A)') 'TPM_FFTW: WARNING failed to export FFTW wisdom to ', &
      & TRIM(ZPATH)
  ENDIF
ELSE
  IF (ALLOCATED(ILENS))   DEALLOCATE(ILENS)
  IF (ALLOCATED(IWORDS))  DEALLOCATE(IWORDS)
  IF (ALLOCATED(IDISPLS)) DEALLOCATE(IDISPLS)
ENDIF

END SUBROUTINE EXPORT_FFTW_WISDOM


SUBROUTINE INIT_PLANS_FFTW(KDLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON

INTEGER(KIND=JPIM) :: INTH
CHARACTER(LEN=4096) :: ZBUF
INTEGER :: IELEN, IESTAT

#include "abor1.intfb.h"

TW%N_MAX=KDLON
ALLOCATE(TW%FFTW_PLANS(TW%N_MAX))
ALLOCATE(TW%N_PLANS(TW%N_MAX))
TW%N_PLANS(:)=0

! pre-size per-thread persistent FFT scratch registry.
IF (.NOT. ALLOCATED(ZFFT_PERSIST_PTRS)) THEN
  INTH = OMP_GET_MAX_THREADS()
  IF (INTH < 1) INTH = 1
  ALLOCATE(ZFFT_PERSIST_PTRS(INTH))
  ALLOCATE(ZFFT_PERSIST_CAPS(INTH))
  ZFFT_PERSIST_PTRS(:) = C_NULL_PTR
  ZFFT_PERSIST_CAPS(:) = 0_C_SIZE_T
ENDIF

! Decide if using FFTW "measure" mode and importing/exporting wisdom
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_FFTW_WISDOM', VALUE=ZBUF, &
  & LENGTH=IELEN, STATUS=IESTAT)
LUSE_MEASURE = (IESTAT == 0 .AND. IELEN > 0 .AND. IELEN <= LEN(ZBUF))

! Import previous FFTW wisdom if it exists, does nothing if it doesn't exist
CALL IMPORT_FFTW_WISDOM

RETURN
END SUBROUTINE INIT_PLANS_FFTW


! ensure OMP thread's persistent FFTW scratch buffer is at least 
! KSIZE_COMPLEX complex elements. Grows on demand by freeing the old
! FFTW allocation and re-allocating via FFTW_ALLOC_COMPLEX, preserving SIMD
! alignment required by MEASURE plans
SUBROUTINE ENSURE_FFT_BUFFER(KSIZE_COMPLEX, PTR_OUT)
INTEGER(C_SIZE_T), INTENT(IN)  :: KSIZE_COMPLEX
TYPE(C_PTR),       INTENT(OUT) :: PTR_OUT
INTEGER(KIND=JPIM) :: ITID
INTEGER(C_SIZE_T)  :: ISIZE

ISIZE = MAX(KSIZE_COMPLEX, 1_C_SIZE_T)
ITID = OMP_GET_THREAD_NUM() + 1

IF (ZFFT_PERSIST_CAPS(ITID) < ISIZE) THEN
  IF (C_ASSOCIATED(ZFFT_PERSIST_PTRS(ITID))) THEN
    IF (JPRB == JPRD) THEN
      CALL FFTW_FREE(ZFFT_PERSIST_PTRS(ITID))
    ELSE
      CALL FFTWF_FREE(ZFFT_PERSIST_PTRS(ITID))
    END IF
  END IF
  IF (JPRB == JPRD) THEN
    ZFFT_PERSIST_PTRS(ITID) = FFTW_ALLOC_COMPLEX(ISIZE)
  ELSE
    ZFFT_PERSIST_PTRS(ITID) = FFTWF_ALLOC_COMPLEX(ISIZE)
  END IF
  ZFFT_PERSIST_CAPS(ITID) = ISIZE
END IF
PTR_OUT = ZFFT_PERSIST_PTRS(ITID)
END SUBROUTINE ENSURE_FFT_BUFFER


SUBROUTINE CREATE_PLAN_FFTW(KPLAN,KTYPE,KN,KLOT)
INTEGER(KIND=JPIB),INTENT(OUT) :: KPLAN
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE,KN,KLOT

INTEGER(KIND=JPIB) :: IPLAN
INTEGER(KIND=JPIM) :: IRANK, ISTRIDE
INTEGER(KIND=JPIM) :: JL
INTEGER(KIND=JPIM) :: IRDIST,ICDIST,IN(1),IEMBED(1)
INTEGER(C_INT)     :: IFLAG
REAL(KIND=JPRB), POINTER :: ZDUM(:)
TYPE(C_PTR) :: ZDUMP
LOGICAL :: LLFOUND
LOGICAL, PARAMETER :: LLRESTRICT_PLANS=.TRUE.
TYPE(FFTW_PLAN),POINTER :: CURR_FFTW_PLAN,START_FFTW_PLAN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE, ZHOOK_HANDLE2
IF (LHOOK) CALL DR_HOOK('CREATE_PLAN_FFTW',0,ZHOOK_HANDLE)

IF( KN > TW%N_MAX )THEN
  CALL ABOR1('CREATE_PLAN_FFTW: KN > N_MAX THAT WAS INITIALISED IN INIT_PLANS_FFTW')
ENDIF

IRANK=1
ISTRIDE=1
IN(1)=KN
IEMBED(1)=IN(1)
ICDIST=KN/2+1
IRDIST=ICDIST*2

!$OMP CRITICAL (FFTW_CREATE)
LLFOUND=.FALSE.
IF( TW%FFTW_PLANS(KN)%NPLAN_ID /= 123456 )THEN
  WRITE(*,'("CREATE_PLAN_FFTW.1: PLAN_ID=",I10)')TW%FFTW_PLANS(KN)%NPLAN_ID
  CALL ABOR1('CREATE_PLAN_FFTW.1: NPLAN_ID /= 123456')
ENDIF
CURR_FFTW_PLAN=>TW%FFTW_PLANS(KN)
IF( CURR_FFTW_PLAN%NPLAN_ID /= 123456 )THEN
  WRITE(*,'("CREATE_PLAN_FFTW.2: PLAN_ID=",I10)')CURR_FFTW_PLAN%NPLAN_ID
  CALL ABOR1('CREATE_PLAN_FFTW.2: NPLAN_ID /= 123456')
ENDIF
! search for plan in existing plans
DO JL=1,TW%N_PLANS(KN)
  IF( KLOT == CURR_FFTW_PLAN%NLOT .AND. KTYPE == CURR_FFTW_PLAN%NTYPE )THEN
    LLFOUND=.TRUE.
    IPLAN=CURR_FFTW_PLAN%NPLAN
    EXIT
  ELSEIF( JL /= TW%N_PLANS(KN) )THEN
    CURR_FFTW_PLAN=>CURR_FFTW_PLAN%NEXT_PLAN
    IF( CURR_FFTW_PLAN%NPLAN_ID /= 123456 )THEN
      WRITE(*,'("CREATE_PLAN_FFTW.3: PLAN_ID=",I10)')CURR_FFTW_PLAN%NPLAN_ID
      CALL ABOR1('CREATE_PLAN_FFTW.3: NPLAN_ID /= 123456')
    ENDIF
  ENDIF
ENDDO
IF( .NOT.LLFOUND )THEN
  IF( LLRESTRICT_PLANS )THEN
    IF( TW%N_PLANS(KN) == TW%N_MAX_PLANS )THEN
      ! destroy the plan at the start of the list
!     WRITE(*,'("CREATE_PLAN_FFTW: BEG: DESTROYING A PLAN AT THE START OF THE LIST")')
       IF (JPRB == JPRD) THEN
          CALL DFFTW_DESTROY_PLAN(TW%FFTW_PLANS(KN)%NPLAN)
       ELSE
          CALL SFFTW_DESTROY_PLAN(TW%FFTW_PLANS(KN)%NPLAN)
       END IF
      TW%FFTW_PLANS(KN)%NPLAN_ID=999999
      START_FFTW_PLAN=>TW%FFTW_PLANS(KN)
      TW%FFTW_PLANS(KN)=TW%FFTW_PLANS(KN)%NEXT_PLAN
      ! DEALLOCATE(START_FFTW_PLAN)
      TW%N_PLANS(KN)=TW%N_PLANS(KN)-1
!     WRITE(*,'("CREATE_PLAN_FFTW: END: DESTROYING A PLAN AT THE START OF THE LIST")')
    ENDIF
  ENDIF
  ! Dummy buffer sized for the real plan (ICDIST*KLOT complex = IRDIST*KLOT real,
  ! in-place). FFTW_ESTIMATE does not touch it, but next commit allows optional
  ! use of FFTW_MEASURE, and the correct sizing must be in place from the start.
  IF (JPRB == JPRD) THEN
     ZDUMP=FFTW_ALLOC_COMPLEX(INT(MAX(1_JPIM,ICDIST*KLOT),C_SIZE_T))
  ELSE
     ZDUMP=FFTWF_ALLOC_COMPLEX(INT(MAX(1_JPIM,ICDIST*KLOT),C_SIZE_T))
  END IF
  CALL C_F_POINTER(ZDUMP,ZDUM,[MAX(1_JPIM,IRDIST*KLOT)])
  ! MEASURE (changes results baseline) when ECTRANS_FFTW_WISDOM is set, otherwise
  ! use previous ESTIMATE+NO_SIMD path (bit-identical with previous state).
  IF (LUSE_MEASURE) THEN
    IFLAG = FFTW_MEASURE
  ELSE
    IFLAG = FFTW_ESTIMATE + FFTW_NO_SIMD
  ENDIF
  IF( KTYPE==1 )THEN
     IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_MANY_DFT_C2R',0,ZHOOK_HANDLE2)
     IF (JPRB == JPRD) THEN
        CALL DFFTW_PLAN_MANY_DFT_C2R(IPLAN,IRANK,IN,KLOT,ZDUM,IEMBED,ISTRIDE,ICDIST,&
             & ZDUM,IEMBED,ISTRIDE,IRDIST,IFLAG)
     ELSE
        CALL SFFTW_PLAN_MANY_DFT_C2R(IPLAN,IRANK,IN,KLOT,ZDUM,IEMBED,ISTRIDE,ICDIST,&
             & ZDUM,IEMBED,ISTRIDE,IRDIST,IFLAG)
     END IF
     IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_MANY_DFT_C2R',1,ZHOOK_HANDLE2)
  ELSEIF( KTYPE==-1 )THEN
     IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_MANY_DFT_R2C',0,ZHOOK_HANDLE2)
     IF (JPRB == JPRD) THEN
        CALL DFFTW_PLAN_MANY_DFT_R2C(IPLAN,IRANK,IN,KLOT,ZDUM,IEMBED,ISTRIDE,IRDIST,&
             & ZDUM,IEMBED,ISTRIDE,ICDIST,IFLAG)
     ELSE
        CALL SFFTW_PLAN_MANY_DFT_R2C(IPLAN,IRANK,IN,KLOT,ZDUM,IEMBED,ISTRIDE,IRDIST,&
             & ZDUM,IEMBED,ISTRIDE,ICDIST,IFLAG)
     END IF
     IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_MANY_DFT_R2C',1,ZHOOK_HANDLE2)
  ELSE
    CALL ABOR1('FFTW_PLAN: INVALID KTYPE')
  ENDIF
  IF (JPRB == JPRD) THEN
     CALL FFTW_FREE(ZDUMP)
  ELSE
     CALL FFTWF_FREE(ZDUMP)
  END IF
  KPLAN=IPLAN
  TW%N_PLANS(KN)=TW%N_PLANS(KN)+1
  IF( TW%N_PLANS(KN) /= 1 )THEN
    ALLOCATE(CURR_FFTW_PLAN%NEXT_PLAN)
    CURR_FFTW_PLAN=>CURR_FFTW_PLAN%NEXT_PLAN
  ENDIF
  IF( CURR_FFTW_PLAN%NPLAN_ID /= 123456 )THEN
    WRITE(*,'("CREATE_PLAN_FFTW.4: PLAN_ID=",I10)')CURR_FFTW_PLAN%NPLAN_ID
    CALL ABOR1('CREATE_PLAN_FFTW.4: NPLAN_ID /= 123456')
  ENDIF
  CURR_FFTW_PLAN%NPLAN=IPLAN
  CURR_FFTW_PLAN%NLOT=KLOT
  CURR_FFTW_PLAN%NTYPE=KTYPE
  CURR_FFTW_PLAN%NEXT_PLAN=>NULL()
! write(*,'("CREATE_PLAN_FFTW: KN=",I5," NPLANS=",I3," KLOT=",I6," KTYPE=",I2,&
!  & " NEW IPLAN=",Z16)')KN,TW%N_PLANS(KN),KLOT,KTYPE,IPLAN
ELSE
  KPLAN=IPLAN
! write(*,'("CREATE_PLAN_FFTW: KN=",I5," NPLANS=",I3," KLOT=",I6," KTYPE=",I2,&
!  & " CUR IPLAN=",Z16)')KN,TW%N_PLANS(KN),KLOT,KTYPE,IPLAN
ENDIF
!$OMP END CRITICAL (FFTW_CREATE)

IF (LHOOK) CALL DR_HOOK('CREATE_PLAN_FFTW',1,ZHOOK_HANDLE)
RETURN
END SUBROUTINE CREATE_PLAN_FFTW


SUBROUTINE DESTROY_PLAN_FFTW(KPLAN)
INTEGER(KIND=JPIB),INTENT(IN) :: KPLAN
!$OMP CRITICAL (FFTW_DESTROY)
IF (JPRB == JPRD) THEN
   CALL DFFTW_DESTROY_PLAN(KPLAN)
ELSE
   CALL SFFTW_DESTROY_PLAN(KPLAN)
END IF
!$OMP END CRITICAL (FFTW_DESTROY)
RETURN
END SUBROUTINE DESTROY_PLAN_FFTW


SUBROUTINE DESTROY_PLANS_FFTW
INTEGER(KIND=JPIM) :: JL, JN
INTEGER(KIND=JPIM) :: JT
TYPE(FFTW_PLAN),POINTER :: CURR_FFTW_PLAN, NEXT_FFTW_PLAN
DO JN=1,TW%N_MAX
  CURR_FFTW_PLAN=>TW%FFTW_PLANS(JN)
  DO JL=1,TW%N_PLANS(JN)
    CALL DESTROY_PLAN_FFTW(CURR_FFTW_PLAN%NPLAN)
    NEXT_FFTW_PLAN=>CURR_FFTW_PLAN%NEXT_PLAN
    IF( JL /= 1 ) THEN
      DEALLOCATE( CURR_FFTW_PLAN )
    ENDIF
    CURR_FFTW_PLAN => NEXT_FFTW_PLAN
  ENDDO
ENDDO
IF( ASSOCIATED(TW) ) THEN
  IF( ASSOCIATED(TW%FFTW_PLANS) )  DEALLOCATE(TW%FFTW_PLANS)
  IF( ALLOCATED(TW%N_PLANS) )     DEALLOCATE(TW%N_PLANS)
  TW%N_MAX=0
ENDIF

! free per-thread persistent FFT scratch buffers. The slot arrays
! themselves remain allocated so a later INIT_PLANS_FFTW + EXEC_FFTW cycle
! (e.g. another resolution) can reuse the registry
IF (ALLOCATED(ZFFT_PERSIST_PTRS)) THEN
  DO JT = 1, SIZE(ZFFT_PERSIST_PTRS)
    IF (C_ASSOCIATED(ZFFT_PERSIST_PTRS(JT))) THEN
      IF (JPRB == JPRD) THEN
        CALL FFTW_FREE(ZFFT_PERSIST_PTRS(JT))
      ELSE
        CALL FFTWF_FREE(ZFFT_PERSIST_PTRS(JT))
      END IF
      ZFFT_PERSIST_PTRS(JT) = C_NULL_PTR
    END IF
    ZFFT_PERSIST_CAPS(JT) = 0_C_SIZE_T
  END DO
END IF

! export wisdom learned if ECTRANS_FFTW_WISDOM is set
CALL EXPORT_FFTW_WISDOM

RETURN
END SUBROUTINE DESTROY_PLANS_FFTW

SUBROUTINE EXEC_FFTW(KTYPE,KRLEN,KCLEN,KOFF,KFIELDS,LD_ALL,PREEL,KPLAN)

INTEGER(KIND=JPIM),INTENT(IN)   :: KTYPE
INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
INTEGER(KIND=JPIM),INTENT(IN)   :: KFIELDS
LOGICAL           ,INTENT(IN)   :: LD_ALL
REAL(KIND=JPRB), INTENT(INOUT)  :: PREEL(:,:)
INTEGER(KIND=JPIB),INTENT(IN), OPTIONAL :: KPLAN ! pre-resolved FFTW plan

REAL(KIND=JPRB), POINTER :: ZFFT(:,:)
REAL(KIND=JPRB), POINTER :: ZFFT1(:)
TYPE(C_PTR) :: ZFFTP, ZFFT1P

INTEGER(KIND=JPIM) :: JJ,JF

INTEGER(KIND=JPIB) :: IPLAN_C2R, IPLAN_C2R1
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE, ZHOOK_HANDLE2
REAL(KIND=JPRB) :: ZINV

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',0,ZHOOK_HANDLE)

IF ( (KTYPE /= -1) .AND. (KTYPE /=1) ) THEN
  CALL ABOR1('TPM_FFTW:EXEC_FFTW : WRONG VALUE KTYPE')
ENDIF

! Reciprocal computed once; only used on the LUSE_MEASURE branch, where
! the bit-id wrt previous state already lost by using FFTW_MEASURE
ZINV = 1.0_JPRB/REAL(KRLEN,JPRB)

IF( LD_ALL )THEN
  IF (PRESENT(KPLAN)) THEN
    IPLAN_C2R = KPLAN
  ELSE
    CALL CREATE_PLAN_FFTW(IPLAN_C2R,KTYPE,KRLEN,KFIELDS)
  ENDIF
  ! per-thread persistent scratch (replaces FFTW_ALLOC_COMPLEX/FFTW_FREE)
  CALL ENSURE_FFT_BUFFER(INT(KCLEN/2*KFIELDS,C_SIZE_T), ZFFTP)
  CALL C_F_POINTER(ZFFTP,ZFFT,[KCLEN,KFIELDS])
  IF (KTYPE==1) THEN
    DO JF=1,KFIELDS
      DO JJ=1,KCLEN
        ZFFT(JJ,JF) =PREEL(JF,KOFF+JJ-1)
      ENDDO
    ENDDO
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',0,ZHOOK_HANDLE2)
    IF (JPRB == JPRD) THEN
       CALL DFFTW_EXECUTE_DFT_C2R(IPLAN_C2R,ZFFT,ZFFT)
    ELSE
       CALL SFFTW_EXECUTE_DFT_C2R(IPLAN_C2R,ZFFT,ZFFT)
    END IF
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',1,ZHOOK_HANDLE2)
    DO JJ=1,KRLEN
      DO JF=1,KFIELDS
        PREEL(JF,KOFF+JJ-1)=ZFFT(JJ,JF)
      ENDDO
    ENDDO
  ELSE
    DO JF=1,KFIELDS
      DO JJ=1,KRLEN
        ZFFT(JJ,JF) =PREEL(JF,KOFF+JJ-1)
      ENDDO
    ENDDO
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',0,ZHOOK_HANDLE2)
    IF (JPRB == JPRD) THEN
       CALL DFFTW_EXECUTE_DFT_R2C(IPLAN_C2R,ZFFT,ZFFT)
    ELSE
       CALL SFFTW_EXECUTE_DFT_R2C(IPLAN_C2R,ZFFT,ZFFT)
    END IF
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',1,ZHOOK_HANDLE2)
    IF (LUSE_MEASURE) THEN
      DO JJ=1,KCLEN
        DO JF=1,KFIELDS
          PREEL(JF,KOFF+JJ-1)=ZFFT(JJ,JF)*ZINV
        ENDDO
      ENDDO
    ELSE
      DO JJ=1,KCLEN
        DO JF=1,KFIELDS
          PREEL(JF,KOFF+JJ-1)=ZFFT(JJ,JF)/REAL(KRLEN,JPRB)
        ENDDO
      ENDDO
    ENDIF
  ENDIF
ELSE
  IF (PRESENT(KPLAN)) THEN
    IPLAN_C2R1 = KPLAN
  ELSE
    CALL CREATE_PLAN_FFTW(IPLAN_C2R1,KTYPE,KRLEN,1)
  ENDIF
  ! per-thread persistent scratch (replaces FFTW_ALLOC_COMPLEX/FFTW_FREE)
  CALL ENSURE_FFT_BUFFER(INT(KCLEN/2,C_SIZE_T), ZFFT1P)
  CALL C_F_POINTER(ZFFT1P,ZFFT1,[KCLEN])
  IF (KTYPE==1) THEN
    DO JF=1,KFIELDS
      DO JJ=1,KCLEN
        ZFFT1(JJ) =PREEL(JF,KOFF+JJ-1)
      ENDDO
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',0,ZHOOK_HANDLE2)
      IF (JPRB == JPRD) THEN
         CALL DFFTW_EXECUTE_DFT_C2R(IPLAN_C2R1,ZFFT1,ZFFT1)
      ELSE
         CALL SFFTW_EXECUTE_DFT_C2R(IPLAN_C2R1,ZFFT1,ZFFT1)
      END IF
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',1,ZHOOK_HANDLE2)
      DO JJ=1,KRLEN
        PREEL(JF,KOFF+JJ-1)=ZFFT1(JJ)
      ENDDO
    ENDDO
  ELSE
    DO JF=1,KFIELDS
      DO JJ=1,KRLEN
        ZFFT1(JJ) =PREEL(JF,KOFF+JJ-1)
      ENDDO
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',0,ZHOOK_HANDLE2)
      IF (JPRB == JPRD) THEN
         CALL DFFTW_EXECUTE_DFT_R2C(IPLAN_C2R1,ZFFT1,ZFFT1)
      ELSE
         CALL SFFTW_EXECUTE_DFT_R2C(IPLAN_C2R1,ZFFT1,ZFFT1)
      END IF
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',1,ZHOOK_HANDLE2)
      IF (LUSE_MEASURE) THEN
        DO JJ=1,KCLEN
          PREEL(JF,KOFF+JJ-1)=ZFFT1(JJ)*ZINV
        ENDDO
      ELSE
        DO JJ=1,KCLEN
          PREEL(JF,KOFF+JJ-1)=ZFFT1(JJ)/REAL(KRLEN,JPRB)
        ENDDO
      ENDIF
    ENDDO
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',1,ZHOOK_HANDLE)
END SUBROUTINE EXEC_FFTW

SUBROUTINE EXEC_EFFTW(KTYPE,KRLEN,KCLEN,KOFF,KFIELDS,LD_ALL,PREEL)

INTEGER(KIND=JPIM),INTENT(IN)   :: KTYPE
INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
INTEGER(KIND=JPIM),INTENT(IN)   :: KFIELDS
LOGICAL           ,INTENT(IN)   :: LD_ALL
REAL(KIND=JPRB), INTENT(INOUT)  :: PREEL(:,:)

REAL(KIND=JPRB), POINTER :: ZFFT(:,:)
REAL(KIND=JPRB), POINTER :: ZFFT1(:)
TYPE(C_PTR) :: ZFFTP, ZFFT1P

INTEGER(KIND=JPIM) :: JJ,JF

INTEGER(KIND=JPIB) :: IPLAN_C2R, IPLAN_C2R1
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE, ZHOOK_HANDLE2
REAL(KIND=JPRB) :: ZINV

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('EXEC_EFFTW',0,ZHOOK_HANDLE)

IF ( (KTYPE /= -1) .AND. (KTYPE /=1) ) THEN
  CALL ABOR1('TPM_FFTW:EXEC_EFFTW : WRONG VALUE KTYPE')
ENDIF

ZINV = 1.0_JPRB/REAL(KRLEN,JPRB)

IF( LD_ALL )THEN
  CALL CREATE_PLAN_FFTW(IPLAN_C2R,KTYPE,KRLEN,KFIELDS)
  ! per-thread persistent scratch (replaces FFTW_ALLOC_COMPLEX/FFTW_FREE)
  CALL ENSURE_FFT_BUFFER(INT(KCLEN/2*KFIELDS,C_SIZE_T), ZFFTP)
  CALL C_F_POINTER(ZFFTP,ZFFT,[KCLEN,KFIELDS])
  IF (KTYPE==1) THEN
    DO JF=1,KFIELDS
      DO JJ=1,KCLEN
        ZFFT(JJ,JF) =PREEL(KOFF+JJ-1,JF)
      ENDDO
    ENDDO
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',0,ZHOOK_HANDLE2)
    IF (JPRB == JPRD) THEN
       CALL DFFTW_EXECUTE_DFT_C2R(IPLAN_C2R,ZFFT,ZFFT)
    ELSE
       CALL SFFTW_EXECUTE_DFT_C2R(IPLAN_C2R,ZFFT,ZFFT)
    END IF
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',1,ZHOOK_HANDLE2)
    DO JF=1,KFIELDS
      DO JJ=1,KRLEN
        PREEL(KOFF+JJ-1,JF)=ZFFT(JJ,JF)
      ENDDO
    ENDDO
  ELSE
    DO JF=1,KFIELDS
      DO JJ=1,KRLEN
        ZFFT(JJ,JF) =PREEL(KOFF+JJ-1,JF)
      ENDDO
    ENDDO
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',0,ZHOOK_HANDLE2)
    IF (JPRB == JPRD) THEN
       CALL DFFTW_EXECUTE_DFT_R2C(IPLAN_C2R,ZFFT,ZFFT)
    ELSE
       CALL SFFTW_EXECUTE_DFT_R2C(IPLAN_C2R,ZFFT,ZFFT)
    END IF
    IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',1,ZHOOK_HANDLE2)
    IF (LUSE_MEASURE) THEN
      DO JF=1,KFIELDS
        DO JJ=1,KCLEN
          PREEL(KOFF+JJ-1,JF)=ZFFT(JJ,JF)*ZINV
        ENDDO
      ENDDO
    ELSE
      DO JF=1,KFIELDS
        DO JJ=1,KCLEN
          PREEL(KOFF+JJ-1,JF)=ZFFT(JJ,JF)/REAL(KRLEN,JPRB)
        ENDDO
      ENDDO
    ENDIF
  ENDIF
ELSE
  CALL CREATE_PLAN_FFTW(IPLAN_C2R1,KTYPE,KRLEN,1)
  ! per-thread persistent scratch (replaces FFTW_ALLOC_COMPLEX/FFTW_FREE)
  CALL ENSURE_FFT_BUFFER(INT(KCLEN/2,C_SIZE_T), ZFFT1P)
  CALL C_F_POINTER(ZFFT1P,ZFFT1,[KCLEN])
  IF (KTYPE==1) THEN
    DO JF=1,KFIELDS
      DO JJ=1,KCLEN
        ZFFT1(JJ) =PREEL(KOFF+JJ-1,JF)
      ENDDO
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',0,ZHOOK_HANDLE2)
      IF (JPRB == JPRD) THEN
         CALL DFFTW_EXECUTE_DFT_C2R(IPLAN_C2R1,ZFFT1,ZFFT1)
      ELSE
         CALL SFFTW_EXECUTE_DFT_C2R(IPLAN_C2R1,ZFFT1,ZFFT1)
      END IF
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',1,ZHOOK_HANDLE2)
      DO JJ=1,KRLEN
        PREEL(KOFF+JJ-1,JF)=ZFFT1(JJ)
      ENDDO
    ENDDO
  ELSE
    DO JF=1,KFIELDS
      DO JJ=1,KRLEN
        ZFFT1(JJ) =PREEL(KOFF+JJ-1,JF)
      ENDDO
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',0,ZHOOK_HANDLE2)
      IF (JPRB == JPRD) THEN
         CALL DFFTW_EXECUTE_DFT_R2C(IPLAN_C2R1,ZFFT1,ZFFT1)
      ELSE
         CALL SFFTW_EXECUTE_DFT_R2C(IPLAN_C2R1,ZFFT1,ZFFT1)
      END IF
      IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',1,ZHOOK_HANDLE2)
      IF (LUSE_MEASURE) THEN
        DO JJ=1,KCLEN
          PREEL(KOFF+JJ-1,JF)=ZFFT1(JJ)*ZINV
        ENDDO
      ELSE
        DO JJ=1,KCLEN
          PREEL(KOFF+JJ-1,JF)=ZFFT1(JJ)/REAL(KRLEN,JPRB)
        ENDDO
      ENDIF
    ENDDO
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('EXEC_EFFTW',1,ZHOOK_HANDLE)
END SUBROUTINE EXEC_EFFTW

END MODULE TPM_FFTW
